"""Lab 04 — Forcing on the spine model (companion to book/ch04_forcing.md).

Builds the 7-condition spine model (depth-2 binary tree, atoms a = left
subtree, b = leaves; J_adm generated by the single root requirement
"leave the void") and prints the forcing tables the chapter reads off.
Assertions lock every value the chapter quotes: if the kernel drifts,
this lab fails and book_audit fails the build.

Run: python book/labs/lab04_forcing.py    (exit 0 iff all chapter facts hold)
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "verification" / "kernel"))

from spine import (  # noqa: E402
    Model,
    DenseTopology,
    GeneratedTopology,
    binary_tree,
    atom,
    neg,
    show,
)

CHECKS: list[str] = []


def expect(cond: bool, label: str) -> None:
    print(f"  [{'ok  ' if cond else 'FAIL'}] {label}")
    if not cond:
        CHECKS.append(label)


def main() -> int:
    P = binary_tree(2)
    V = {
        "a": {q for q in P.elements if q.startswith("0")},   # left subtree
        "b": set(P.leaves),                                   # all leaves
    }
    M = Model(P, V)
    J_nn = DenseTopology(P)
    J_adm = GeneratedTopology(P, {"r": [frozenset(set(P.elements) - {"r"})]})

    print("spine model: conditions r > {0,1} > {00,01,10,11};")
    print("V(a) = left subtree {0,00,01};  V(b) = leaves {00,01,10,11};")
    print("J_adm generated by one requirement on r: 'leave the void'\n")

    # ---- the forcing table the chapter prints -----------------------------
    formulas = [atom("a"), atom("b"), neg(atom("a")), neg(atom("b")), neg(neg(atom("b")))]
    memo_n: dict = {}
    memo_a: dict = {}
    header = f"{'':6}" + "".join(f"{show(f):>8}" for f in formulas)
    print("forcing table, dense reading ||-_nn   (x = forces)")
    print(header)
    for p in P.elements:
        row = "".join(
            f"{'x' if M.forces(J_nn, p, f, memo_n) else '.':>8}" for f in formulas
        )
        print(f"{p:>6}{row}")
    print("\nforcing table, calibrated reading ||-_adm")
    print(header)
    for p in P.elements:
        row = "".join(
            f"{'x' if M.forces(J_adm, p, f, memo_a) else '.':>8}" for f in formulas
        )
        print(f"{p:>6}{row}")
    print()

    # ---- chapter facts, locked --------------------------------------------
    print("chapter facts:")
    expect(M.forces(J_nn, "0", atom("a"), memo_n)
           and M.forces(J_adm, "0", atom("a"), memo_a),
           "0 forces a under BOTH readings (its whole cone stabilizes a)")
    expect(not M.forces(J_nn, "r", atom("a"), memo_n),
           "r does not force a: below 1 nothing stabilizes a (not dense)")
    expect(M.forces(J_nn, "r", atom("b"), memo_n),
           "r forces b under ||-_nn: the leaf set is dense below r")
    expect(not M.forces(J_adm, "r", atom("b"), memo_a),
           "r does NOT force b under ||-_adm: the leaf sieve is no J_adm-cover"
           " (the strictness the Site Bound allows)")
    expect(M.forces(J_nn, "1", neg(atom("a")), memo_n),
           "1 forces ~a: no refinement of 1 ever stabilizes a (torsion at 1)")
    expect(not M.forces(J_nn, "r", neg(atom("a")), memo_n),
           "r does not force ~a: condition 0 below r forces a")

    # persistence spot check (lem:pers): what r forces, 0 forces
    pers = all(
        (not M.forces(J_nn, "r", f, memo_n)) or M.forces(J_nn, "0", f, memo_n)
        for f in formulas
    )
    expect(pers, "persistence: everything r forces, its refinement 0 forces")

    # deciding sets are order-dense (lem:dec) for atom a
    dec_a = {
        q for q in P.elements
        if M.forces(J_nn, q, atom("a"), memo_n)
        or M.forces(J_nn, q, neg(atom("a")), memo_n)
    }
    dense = all(any(s in dec_a for s in P.down[q]) for q in P.elements)
    expect(dense and "r" not in dec_a,
           "deciding set D_a = everything except r: dense in the order, "
           "while r itself stays undecided (bivalence lives on branches)")

    # torsion vs clause negation come apart on the compound ~b (rem:torsion)
    clause = M.forces(J_nn, "r", neg(neg(atom("b"))), memo_n)
    torsion_reading = all(M.stab(q, neg(atom("b"))) for q in P.down["r"])
    expect(clause and not torsion_reading,
           "compound divergence: r forces ~~b by the clause (nobody can force"
           " ~b) yet ~b is nowhere classically stable — the two readings of"
           " 'permanently refuted' agree on atoms only")

    print()
    if CHECKS:
        print(f"LAB 04 FAILURES: {CHECKS}")
        return 1
    print("Lab 04 OK — every fact quoted in chapter 04 holds on the kernel")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
