"""Lab 03 — Sieves, covers, and two topologies on the spine model
(companion to book/ch03_sieves_covers_topologies.md).

Enumerates every sieve on every condition of the 7-condition spine,
builds J_nn (dense sieves) and J_adm (generated by one root requirement,
"leave the void") via verification/kernel/spine.py, and checks by brute
force: both are Grothendieck topologies (maximal sieve present, pullback
stable, transitive/local), the Site Bound J_adm subset-or-equal J_nn
holds at every condition, and the containment is *strict* (J_nn has
covers J_adm does not) — the computational witness for strictness the
chapter discusses in prose.

Run: python book/labs/lab03_topologies.py    (exit 0 iff all chapter facts hold)
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "verification" / "kernel"))

from spine import DenseTopology, GeneratedTopology, binary_tree  # noqa: E402

CHECKS: list[str] = []


def expect(cond: bool, label: str) -> None:
    print(f"  [{'ok  ' if cond else 'FAIL'}] {label}")
    if not cond:
        CHECKS.append(label)


def is_grothendieck(P, J) -> tuple[bool, bool, bool]:
    """(maximal-sieve present, pullback-stable, transitive/local) at every p."""
    maximal_ok = all(J.covers(p, P.down[p]) for p in P.elements)
    pullback_ok = True
    for p in P.elements:
        for S in P.sieves_on(p):
            if not J.covers(p, S):
                continue
            for q in P.down[p]:
                pb = S & P.down[q]
                if not J.covers(q, pb):
                    pullback_ok = False
    local_ok = True
    for p in P.elements:
        for S in P.sieves_on(p):
            if J.covers(p, S):
                continue
            # find any cover R of p such that S is covered at every q in R
            covers_of_p = [T for T in P.sieves_on(p) if J.covers(p, T)]
            if any(
                all(J.covers(q, S & P.down[q]) for q in R) for R in covers_of_p
            ):
                local_ok = False  # local character would have forced S in
    return maximal_ok, pullback_ok, local_ok


def main() -> int:
    P = binary_tree(2)
    J_nn = DenseTopology(P)
    J_adm = GeneratedTopology(P, {"r": [frozenset(set(P.elements) - {"r"})]})

    print("spine model, same as ch02/04; sieve counts per condition:")
    for p in P.elements:
        print(f"  sieves_on({p:>2}) = {len(P.sieves_on(p))}")

    # ---- sieve counts: a sanity fact the chapter quotes -------------------
    expect(len(P.sieves_on("r")) == 26, "26 sieves on r: down-closed subsets of a 7-element tree")
    expect(len(P.sieves_on("00")) == 2, "2 sieves on a leaf: empty, and the maximal one (down(leaf) is a singleton)")

    # ---- both are genuine Grothendieck topologies --------------------------
    max_nn, pb_nn, loc_nn = is_grothendieck(P, J_nn)
    expect(
        max_nn and pb_nn and loc_nn,
        "J_nn: maximal sieve covers, pullback-stable, local character holds",
    )
    max_adm, pb_adm, loc_adm = is_grothendieck(P, J_adm)
    expect(
        max_adm and pb_adm and loc_adm,
        "J_adm: maximal sieve covers, pullback-stable, local character holds",
    )

    # ---- the Site Bound: J_adm(p) subset-or-equal J_nn(p) everywhere ------
    bound_holds = True
    for p in P.elements:
        for S in P.sieves_on(p):
            if J_adm.covers(p, S) and not J_nn.covers(p, S):
                bound_holds = False
    expect(bound_holds, "Site Bound (lem:sitebound): every J_adm-cover is a J_nn-cover, at every condition")

    # ---- strictness: the containment is proper -----------------------------
    witness = None
    for p in P.elements:
        for S in P.sieves_on(p):
            if J_nn.covers(p, S) and not J_adm.covers(p, S):
                witness = (p, S)
                break
        if witness:
            break
    expect(witness is not None, "strictness: some J_nn-cover is NOT a J_adm-cover (containment is proper)")
    if witness:
        p, S = witness
        print(f"\n  witness of strictness: at p={p!r}, S={sorted(S)} is J_nn-dense but not a J_adm-cover")

    # ---- the generator itself: "leave the void" ---------------------------
    everyone_but_root = frozenset(set(P.elements) - {"r"})
    expect(
        J_adm.covers("r", everyone_but_root),
        "the single J_adm generator on r ('leave the void') is itself a cover",
    )
    expect(
        J_nn.covers("r", everyone_but_root),
        "and it is dense too, consistent with the Site Bound",
    )

    print(f"\n{len(CHECKS)} failures.")
    return 1 if CHECKS else 0


if __name__ == "__main__":
    sys.exit(main())
