"""Human projection of the machine-readable Principia statement bindings."""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs" / "23_PS_BINDING_LEDGER.md"


def atlas_path() -> Path | None:
    configured = os.environ.get("PRINCIPIA_ATLAS")
    candidates = [
        Path(configured) if configured else None,
        ROOT.parent / "principia" / "bib" / "principia_atlas.json",
        ROOT / "verification" / "principia_atlas.json",
    ]
    return next((p for p in candidates if p and p.is_file()), None)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    atlas_file = atlas_path()
    if atlas_file is None:
        print("Principia atlas not found; binding projection skipped")
        return 0
    atlas = json.loads(atlas_file.read_text(encoding="utf-8"))
    nodes = {n.get("label") or n.get("id"): n for n in atlas["nodes"]}
    bindings = json.loads(
        (ROOT / "verification" / "bindings.json").read_text(encoding="utf-8")
    )["bindings"]
    principia = [b for b in bindings if b.get("source") == "principia"]
    grouped: dict[str, list[dict]] = defaultdict(list)
    for binding in principia:
        grouped[binding["math_id"]].append(binding)

    coverage = {}
    for path in sorted((ROOT / "verification").glob("*_lean_map.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        for entry in doc.get("entries", []):
            coverage.setdefault(entry["atlas_id"], entry.get("coverage", "mapped"))

    rows_by_book: dict[str, list[dict]] = defaultdict(list)
    for anchor, bound in grouped.items():
        node = nodes.get(anchor, {})
        rows_by_book[node.get("book") or "unknown"].append({
            "anchor": anchor,
            "name": node.get("name") or anchor,
            "line": node.get("line"),
            "coverage": coverage.get(anchor, "bound-only"),
            "artifacts": len({b["artifact"] for b in bound}),
            "declarations": len({b["declares"] for b in bound}),
            "sha": bound[0].get("statement_sha") or "—",
            "attested": all(bool(b.get("attested_in")) for b in bound),
        })

    lines = [
        "# Principia statement-binding ledger",
        "",
        "*Generated by `verification/tools/binding_projection.py` from",
        "`verification/bindings.json`; do not edit by hand.*",
        "",
        "Each row is a Principia atlas anchor with at least one source-hash-pinned",
        "artifact. `bound-only` means the transcription is drift-protected but has",
        "not yet been admitted by a coverage map. `reserved` means the hash matches",
        "mechanically but still awaits human attestation.",
        "",
        f"- Bound declarations: **{len(principia)}**",
        f"- Unique Principia anchors: **{len(grouped)}**",
        f"- Human-attested bindings: **{sum(bool(b.get('attested_in')) for b in principia)}**",
        "",
    ]
    for book in sorted(rows_by_book):
        rows = sorted(rows_by_book[book], key=lambda r: (r["line"] or 0, r["anchor"]))
        lines += [
            f"## {book}",
            "",
            "| anchor | name | coverage | artifacts | declarations | SHA | attestation |",
            "|---|---|---|---:|---:|---|---|",
        ]
        for row in rows:
            state = "attested" if row["attested"] else "reserved"
            name = str(row["name"]).replace("|", "\\|")
            lines.append(
                f"| `{row['anchor']}` | {name} | {row['coverage']} | "
                f"{row['artifacts']} | {row['declarations']} | `{row['sha']}` | {state} |"
            )
        lines.append("")
    text = "\n".join(lines)
    findings = []
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != text:
            findings.append("docs/23_PS_BINDING_LEDGER.md is stale")
    else:
        OUT.write_text(text, encoding="utf-8")
    for finding in findings:
        print("[BINDING_PROJECTION] " + finding)
    print(f"{len(findings)} findings; {len(principia)} bindings projected across "
          f"{len(grouped)} Principia anchors")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
