"""Validate and project Principia Book 5's exact Lean coverage."""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAP = ROOT / "verification" / "book5_lean_map.json"
RECEIPT = ROOT / "selfcompile" / "lean_receipt.json"
PUBLIC = ROOT / "public" / "lean" / "book5.json"
DOC = ROOT / "docs" / "19_BOOK5_LEAN_COVERAGE.md"
PAPER_MACROS = ROOT / "verification" / "papers" / "generated_book5_counts.tex"
CLAIM_TYPES = {"theorem", "proposition", "lemma", "corollary", "axiom"}


def atlas_path() -> Path | None:
    configured = os.environ.get("PRINCIPIA_ATLAS")
    candidates = [
        Path(configured) if configured else None,
        ROOT.parent / "principia" / "bib" / "principia_atlas.json",
        ROOT / "verification" / "principia_atlas.json",
    ]
    return next((p for p in candidates if p and p.is_file()), None)


def render_doc(packet: dict) -> str:
    counts = packet["coverage_counts"]
    lines = [
        "# Book 5 Lean coverage",
        "",
        "*Generated by verification/tools/book5_lean_coverage.py.*",
        "",
        packet["boundary"],
        "",
        f"- Lean declarations in receipt: **{packet['verified_declarations']}**",
        f"- Book 5 anchors mapped: **{packet['mapped_anchors']}**",
        f"- Book 5 claim-bearing atlas nodes: **{packet['atlas']['claim_nodes']}**",
        f"- Unmapped claim-bearing nodes: **{packet['atlas']['unmapped_claim_nodes']}**",
        "- Coverage classes: " + ", ".join(
            f"{key} {value}" for key, value in sorted(counts.items())
        ),
        "",
        "| Principia anchor | coverage | Lean declarations | boundary |",
        "|---|---|---|---|",
    ]
    for entry in packet["entries"]:
        lean = ", ".join(t["name"] for t in entry["theorems"])
        lines.append(
            f"| {entry['atlas_id']} | {entry['coverage']} | {lean} | {entry['note']} |"
        )
    lines += [
        "",
        "## Open claim surface",
        "",
        "These theorem-like Book 5 nodes are not mapped to a Lean declaration yet. "
        "Their paper proofs may be useful, but this package does not call them Lean-verified.",
        "",
    ]
    for node in packet["unmapped_claims"]:
        lines.append(
            f"- {node['id']} ({node['type']}, line {node.get('line', '?')}): "
            f"{node.get('name') or ''}"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    mapping = json.loads(MAP.read_text(encoding="utf-8"))
    receipt = json.loads(RECEIPT.read_text(encoding="utf-8"))
    theorem_by_name = {t["name"]: t for t in receipt["theorems"]}
    findings: list[str] = []

    entries = mapping["entries"]
    ids = [e["atlas_id"] for e in entries]
    if len(ids) != len(set(ids)):
        findings.append("duplicate atlas ids in Book 5 Lean map")

    atlas_file = atlas_path()
    book_nodes: list[dict] = []
    atlas_by_id: dict[str, dict] = {}
    if atlas_file:
        atlas = json.loads(atlas_file.read_text(encoding="utf-8"))
        book_nodes = [n for n in atlas["nodes"] if n.get("book") == "book5"]
        atlas_by_id = {n["id"]: n for n in book_nodes}

    projected = []
    for entry in entries:
        missing = [name for name in entry["lean"] if name not in theorem_by_name]
        if missing:
            findings.append(f"{entry['atlas_id']}: receipt missing {missing}")
        if atlas_by_id and entry["atlas_id"] not in atlas_by_id:
            findings.append(f"{entry['atlas_id']}: absent from Principia atlas")
        projected.append({
            **entry,
            "atlas": {
                key: atlas_by_id.get(entry["atlas_id"], {}).get(key)
                for key in ("type", "name", "file", "line", "proof_status")
            },
            "theorems": [
                theorem_by_name[name] for name in entry["lean"] if name in theorem_by_name
            ],
        })

    mapped = set(ids)
    mapped_theorems = {name for entry in entries for name in entry["lean"]}
    claim_nodes = [n for n in book_nodes if n.get("type") in CLAIM_TYPES]
    unmapped = [
        {key: n.get(key) for key in ("id", "type", "name", "line", "proof_status")}
        for n in claim_nodes if n["id"] not in mapped
    ]
    counts = Counter(e["coverage"] for e in entries)
    packet = {
        "schema": "sketched.book5-lean-coverage.v1",
        "source": mapping["source"],
        "boundary": mapping["boundary"],
        "generated_from": {
            "map": MAP.relative_to(ROOT).as_posix(),
            "receipt": RECEIPT.relative_to(ROOT).as_posix(),
            "principia_atlas": str(atlas_file) if atlas_file else None,
        },
        "verified_declarations": receipt["verified"],
        "mapped_anchors": len(entries),
        "mapped_declarations": len(mapped_theorems),
        "coverage_counts": dict(sorted(counts.items())),
        "atlas": {
            "book5_nodes": len(book_nodes),
            "claim_nodes": len(claim_nodes),
            "unmapped_claim_nodes": len(unmapped),
        },
        "entries": projected,
        "unmapped_claims": unmapped,
        "browser_path": "/book/lean",
        "json_path": "/lean/book5.json",
    }
    public_text = json.dumps(packet, indent=2) + "\n"
    doc_text = render_doc(packet)
    macro_text = (
        "% Generated by book5_lean_coverage.py; do not edit.\n"
        f"\\newcommand{{\\VerifiedDeclarationCount}}{{{packet['verified_declarations']}}}\n"
        f"\\newcommand{{\\MappedBookFiveAnchorCount}}{{{packet['mapped_anchors']}}}\n"
        f"\\newcommand{{\\MappedBookFiveDeclarationCount}}{{{packet['mapped_declarations']}}}\n"
        f"\\newcommand{{\\BookFiveClaimNodeCount}}{{{packet['atlas']['claim_nodes']}}}\n"
        f"\\newcommand{{\\OpenBookFiveClaimCount}}{{{packet['atlas']['unmapped_claim_nodes']}}}\n"
    )

    if args.check:
        if not PUBLIC.is_file() or PUBLIC.read_text(encoding="utf-8") != public_text:
            findings.append("public/lean/book5.json is stale")
        if not DOC.is_file() or DOC.read_text(encoding="utf-8") != doc_text:
            findings.append("docs/19_BOOK5_LEAN_COVERAGE.md is stale")
        if not PAPER_MACROS.is_file() or PAPER_MACROS.read_text(encoding="utf-8") != macro_text:
            findings.append("verification/papers/generated_book5_counts.tex is stale")
    else:
        PUBLIC.parent.mkdir(parents=True, exist_ok=True)
        PUBLIC.write_text(public_text, encoding="utf-8")
        DOC.write_text(doc_text, encoding="utf-8")
        PAPER_MACROS.parent.mkdir(parents=True, exist_ok=True)
        PAPER_MACROS.write_text(macro_text, encoding="utf-8")

    for finding in findings:
        print("[BOOK5_LEAN] " + finding)
    print(
        f"{len(findings)} findings; {len(entries)} mapped anchors; "
        f"{len(theorem_by_name)} verified declarations; {len(unmapped)} open claim nodes"
    )
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
