"""Lean PS ledger audit + projection.

Validates verification/leanps_ledger.json (the machine-readable research
ledger of the Lean PS slice: the shared commuting schema and its two
instances), computes the transitive M/C/O debt closure mechanically, and
regenerates docs/18_LEAN_PS_LEDGER.md from it — the human-readable view is
a projection, never hand-edited.

Findings (exit 1 on any):

  LPS_BAD_STATUS       status not one of P/D/S/M/C/O
  LPS_DUP_ID           duplicate entry id
  LPS_BAD_DEP          depends_on/consumes id resolves to neither an entry
                       nor a declared external
  LPS_FILE_MISSING     formal_source/implementation_source file absent
  LPS_DECL_MISSING     a name in `declares` absent from the formal source
  LPS_P_UNDECLARED     a P entry with a formal source but no declares —
                       "proved" must point at checkable names

Debt discipline: an entry's transitive debt is every reachable id (through
depends_on and consumes, entries and externals alike) whose status is M, C,
or O. "Lean proved it" must never hide an M/C premise — the projection
prints the closure next to every P row.

Run: python verification/tools/leanps_audit.py   (regenerates docs/18)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LEDGER = ROOT / "verification" / "leanps_ledger.json"
DOC = ROOT / "docs" / "18_LEAN_PS_LEDGER.md"

STATUSES = {"P", "D", "S", "M", "C", "O"}


def main() -> int:
    data = json.loads(LEDGER.read_text(encoding="utf-8"))
    entries = data["entries"]
    external = data.get("external", {})
    findings: list[tuple[str, str]] = []

    by_id: dict[str, dict] = {}
    for e in entries:
        if e["id"] in by_id:
            findings.append(("LPS_DUP_ID", e["id"]))
        by_id[e["id"]] = e

    status_of: dict[str, str] = {i: e["status"] for i, e in by_id.items()}
    for x, meta in external.items():
        status_of[x] = meta.get("status", "?")

    for e in entries:
        eid = e["id"]
        if e["status"] not in STATUSES:
            findings.append(("LPS_BAD_STATUS", f"{eid}: {e['status']}"))
        for dep in list(e.get("depends_on", [])) + list(e.get("consumes", [])):
            if dep not in status_of:
                findings.append(("LPS_BAD_DEP", f"{eid} -> {dep}"))
        for key in ("formal_source", "implementation_source"):
            src = e.get(key)
            if src and not (ROOT / src).is_file():
                findings.append(("LPS_FILE_MISSING", f"{eid}: {src}"))
        src = e.get("formal_source")
        decls = e.get("declares", [])
        if src and decls and (ROOT / src).is_file():
            text = (ROOT / src).read_text(encoding="utf-8")
            for d in decls:
                # Lean dot-names declare their suffix
                if d.split(".")[-1] not in text:
                    findings.append(("LPS_DECL_MISSING", f"{eid}: {d} not in {src}"))
        if e["status"] == "P" and src and not decls:
            findings.append(("LPS_P_UNDECLARED", eid))

    def debt(eid: str, seen: frozenset[str] = frozenset()) -> set[str]:
        if eid in seen:
            return set()
        out: set[str] = set()
        if status_of.get(eid) in {"M", "C", "O"}:
            out.add(f"{status_of[eid]}:{eid}")
        e = by_id.get(eid)
        if e:
            for dep in list(e.get("depends_on", [])) + list(e.get("consumes", [])):
                out |= debt(dep, seen | {eid})
        return out

    closures = {e["id"]: sorted(debt(e["id"]) - (
        {f"{e['status']}:{e['id']}"} if e["status"] in {"M", "C", "O"} else set()
    )) for e in entries}

    # ---- projection -------------------------------------------------------
    lines = [
        "# Lean PS ledger",
        "",
        "*Generated by `verification/tools/leanps_audit.py` from",
        "`verification/leanps_ledger.json` — do not edit by hand.*",
        "",
        data["description"],
        "",
        "| id | st | domain | transitive M/C/O debt | declares |",
        "|---|---|---|---|---|",
    ]
    for e in entries:
        d = ", ".join(closures[e["id"]]) or "—"
        decls = ", ".join(f"`{x}`" for x in e.get("declares", [])) or "—"
        lines.append(f"| {e['id']} | {e['status']} | {e['domain']} | {d} | {decls} |")
    lines.append("")
    if external:
        lines.append("External ids consumed: " + ", ".join(
            f"`{x}` ({m.get('status')}; {m.get('where')})" for x, m in external.items()) + ".")
        lines.append("")
    for e in entries:
        lines += [f"## {e['id']} ({e['status']}, {e['domain']})", "", e["statement"], ""]
        if e.get("hypotheses"):
            lines.append("- **Hypotheses:** " + "; ".join(e["hypotheses"]))
        if e.get("depends_on"):
            lines.append("- **Depends on:** " + ", ".join(e["depends_on"]))
        if e.get("consumes"):
            lines.append("- **Consumes:** " + ", ".join(e["consumes"]))
        if closures[e["id"]]:
            lines.append("- **Transitive debt:** " + ", ".join(closures[e["id"]]))
        if e.get("formal_source"):
            lines.append(f"- **Formal source:** `{e['formal_source']}`")
        if e.get("implementation_source"):
            lines.append(f"- **Implementation:** `{e['implementation_source']}`")
        if e.get("falsifier"):
            lines.append("- **Falsifier / negative control:** " + e["falsifier"])
        if e.get("evidence"):
            lines.append("- **Evidence:** " + e["evidence"])
        if e.get("next"):
            lines.append("- **Next closure action:** " + e["next"])
        lines.append("")
    DOC.write_text("\n".join(lines), encoding="utf-8", newline="\n")

    for code, msg in findings:
        print(f"[{code}] {msg}")
    print(f"{len(findings)} findings; {len(entries)} ledger entries; "
          f"projection -> {DOC.relative_to(ROOT)}")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
