"""Operator-correspondence auditor: the math↔engineering trace, checked.

Reads verification/operators.json and verifies:

  MATH_ID_UNKNOWN     math_id does not exist as a node in atlas.json
  CODE_REF_MISSING    a 'realized' entry's file does not exist
  EXPORT_MISSING      a 'realized' entry's named export is absent from the file
  TARGET_HAS_CODE     a 'target' entry claims a code ref (design presented as shipped)
  STATUS_UNKNOWN      status not in {realized, target}
  CAL_ITEM_UNCOVERED  (info) calibration-queue items 1-10 with no operator entry

Then regenerates docs/13_OPERATOR_MAP.md from the JSON, so the human-readable
table can never drift from the checked source of truth.

Exit 1 on any non-info finding.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OPERATORS = ROOT / "verification" / "operators.json"
ATLAS = ROOT / "verification" / "atlas.json"
DOC_OUT = ROOT / "docs" / "13_OPERATOR_MAP.md"

EXPORT_RE = "export\\s+(?:async\\s+)?(?:function|const|let|class|interface|type|enum)\\s+{name}\\b"


def check_export(file: Path, name: str) -> bool:
    if not file.is_file():
        return False
    text = file.read_text(encoding="utf-8")
    return re.search(EXPORT_RE.format(name=re.escape(name)), text) is not None


def main() -> int:
    # Packet mode: in a source-only verification packet the TypeScript tree
    # (and operators.json) are intentionally absent. Skip cleanly rather than
    # failing the suite on files that were never claimed to be present.
    if not (ROOT / "src").is_dir() or not OPERATORS.is_file():
        print("src/ tree or operators.json absent — packet mode; operator "
              "correspondence audit skipped (ships in the operator packet)")
        return 0
    ops = json.loads(OPERATORS.read_text(encoding="utf-8"))
    atlas = json.loads(ATLAS.read_text(encoding="utf-8"))
    atlas_ids = {n["id"] for n in atlas["nodes"]}
    findings: list[tuple[str, str]] = []

    entries = list(ops["operators"]) + list(ops["zero_order_principles"])
    for e in entries:
        label = e.get("label") or e["engineering_operator"][:40]
        mid = e.get("math_id")
        if mid and mid not in atlas_ids:
            findings.append(("MATH_ID_UNKNOWN", f"{label}: '{mid}' not in atlas"))

        status = e.get("status", "realized")  # zero-order principles are realized
        if status not in ("realized", "target"):
            findings.append(("STATUS_UNKNOWN", f"{label}: '{status}'"))
        code = e.get("code")
        if status == "realized":
            if not code:
                findings.append(("CODE_REF_MISSING", f"{label}: realized but no code ref"))
            else:
                f = ROOT / code["file"]
                if not f.is_file():
                    findings.append(("CODE_REF_MISSING", f"{label}: {code['file']} absent"))
                elif not check_export(f, code["export"]):
                    findings.append(
                        ("EXPORT_MISSING", f"{label}: no export '{code['export']}' in {code['file']}")
                    )
        elif status == "target" and code:
            findings.append(("TARGET_HAS_CODE", f"{label}: target entries must not claim code"))

    covered = {e.get("calibration_item") for e in ops["operators"] if e.get("calibration_item")}
    for item in range(1, 11):
        if item not in covered:
            findings.append(("CAL_ITEM_UNCOVERED", f"(info) calibration item {item} has no operator entry"))

    # ---- regenerate the human-readable map ---------------------------------
    lines = [
        "# 13 · Operator map — engineering operators traced to mathematical operators",
        "",
        "**Generated by `verification/tools/operator_audit.py` from",
        "[`../verification/operators.json`](../verification/operators.json) — edit the JSON, not this file.**",
        "Every `realized` row's code reference is mechanically verified on each suite run;",
        "`target` rows are design intent and are checked to claim no code. Paper references",
        f"are to `{ops['paper']}` (atlas node ids).",
        "",
        "## Zero-order design principles (human-labelled calibration data)",
        "",
        "| Label | Mathematical operator | Engineering operator | Code |",
        "|---|---|---|---|",
    ]
    for z in ops["zero_order_principles"]:
        code = f"`{z['code']['file']}#{z['code']['export']}`" if z.get("code") else "—"
        lines.append(
            f"| **{z['label']}** | {z['math_operator']} (`{z['math_id']}`) "
            f"| {z['engineering_operator']} | {code} |"
        )
    lines += [
        "",
        "## Operators",
        "",
        "| Math (atlas id) | Mathematical operator | Engineering operator | Code | Cal. item | Status |",
        "|---|---|---|---|---|---|",
    ]
    for e in ops["operators"]:
        code = f"`{e['code']['file']}#{e['code']['export']}`" if e.get("code") else "—"
        cal = e["calibration_item"] if e.get("calibration_item") else "—"
        lines.append(
            f"| `{e['math_id']}` | {e['math_operator']} | {e['engineering_operator']} "
            f"| {code} | {cal} | {e['status']} |"
        )
    lines += [
        "",
        "## Reading the statuses",
        "",
        "- **realized** — the code exists and exports the named symbol (checked).",
        "  This is S-status in the paper's ledger sense: implementation conformance,",
        "  not proof that the operation realizes the Kripke–Joyal clause it mirrors.",
        "- **target** — design intent from docs/11–12. Presenting these as shipped",
        "  would be exactly the ledger dishonesty the paper forbids; the auditor",
        "  fails the build if a target row acquires a code ref without being",
        "  promoted to realized.",
        "",
        "The calibration queue (paper §6, Assumption 2) is the bridge debt: items",
        "with operator entries are *addressed*, not discharged. Discharging any",
        "item means showing the engineering operator satisfies the mathematical",
        "operator's clause — the open (C) of the correspondence.",
        "",
    ]
    DOC_OUT.write_text("\n".join(lines), encoding="utf-8")

    order = ["MATH_ID_UNKNOWN", "CODE_REF_MISSING", "EXPORT_MISSING",
             "TARGET_HAS_CODE", "STATUS_UNKNOWN", "CAL_ITEM_UNCOVERED"]
    findings.sort(key=lambda f: order.index(f[0]))
    for code, msg in findings:
        print(f"[{code}] {msg}")
    realized = sum(1 for e in ops["operators"] if e["status"] == "realized")
    targets = sum(1 for e in ops["operators"] if e["status"] == "target")
    print(f"\n{len(findings)} findings; {realized} realized + {targets} target operators; "
          f"wrote {DOC_OUT.name}")
    fatal = {"MATH_ID_UNKNOWN", "CODE_REF_MISSING", "EXPORT_MISSING",
             "TARGET_HAS_CODE", "STATUS_UNKNOWN"}
    return 1 if any(c in fatal for c, _ in findings) else 0


if __name__ == "__main__":
    sys.exit(main())
