"""Exact Principia-to-Lean frontier, projected for machines and humans.

The aggregate queue answers "how much remains?".  This projection answers
"exactly which claims remain?" and keeps source location, dependency labels,
SHA-bound artifacts, and source-repair debt visible in one place.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_JSON = ROOT / "verification" / "ps_frontier.json"
OUT_MD = ROOT / "docs" / "22_PS_LEAN_FRONTIER.md"
CLAIM_TYPES = {"theorem", "proposition", "lemma", "corollary", "axiom"}


def atlas_path() -> Path | None:
    configured = os.environ.get("PRINCIPIA_ATLAS")
    candidates = [
        Path(configured) if configured else None,
        ROOT.parent / "principia" / "bib" / "principia_atlas.json",
        ROOT / "verification" / "principia_atlas.json",
    ]
    return next((p for p in candidates if p and p.is_file()), None)


def render(packet: dict) -> str:
    binding = packet["binding_integrity"]
    lines = [
        "# Principia -> Lean exact frontier",
        "",
        "*Generated by `verification/tools/ps_frontier.py`; do not edit by hand.*",
        "",
        "This is the identity-level companion to the aggregate queue. A claim is",
        "open until one of the coverage maps names its atlas anchor. SHA bindings",
        "protect transcriptions from silent source drift, but a reserved binding is",
        "not a human attestation and does not itself count as mapped coverage.",
        "",
        f"- Claims: **{packet['claims_total']}**",
        f"- Mapped: **{packet['mapped_total']}**",
        f"- Open: **{packet['open_total']}**",
        f"- SHA bindings: **{binding['bindings_total']}** "
        f"({binding['human_attested']} human-attested; "
        f"{binding['reserved']} reserved)",
        f"- Unresolved source obligations: **{packet['source_obligations_unresolved']}**",
        "",
        "| book | open claim | source | bound artifacts | dependencies |",
        "|---|---|---|---:|---|",
    ]
    for item in packet["open_claims"]:
        deps = ", ".join(f"`{x}`" for x in item["depends_on"]) or "—"
        lines.append(
            f"| {item['book']} | `{item['id']}` — {item['name']} | "
            f"`{item['file']}:{item['line']}` | {item['binding_count']} | {deps} |"
        )
    lines += [
        "",
        "## Book totals",
        "",
        "| book | claims | mapped | open |",
        "|---|---:|---:|---:|",
    ]
    for row in packet["books"]:
        lines.append(
            f"| {row['book']} | {row['claims']} | {row['mapped']} | {row['open']} |"
        )
    lines += [
        "",
        "`binding_count > 0` means a source-hash-pinned artifact exists but has not",
        "yet been admitted by a coverage map. Source obligations remain separate:",
        "they record where a Lean kernel is conditional or a countermodel exposes a",
        "missing premise in the LaTeX.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    atlas_file = atlas_path()
    if atlas_file is None:
        print("Principia atlas not found; frontier projection skipped")
        return 0

    atlas = json.loads(atlas_file.read_text(encoding="utf-8"))
    maps: dict[str, dict] = {}
    for path in sorted((ROOT / "verification").glob("*_lean_map.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        for entry in doc.get("entries", []):
            maps.setdefault(entry["atlas_id"], entry)

    binding_doc = json.loads(
        (ROOT / "verification" / "bindings.json").read_text(encoding="utf-8")
    )
    bound: dict[str, list[dict]] = defaultdict(list)
    for binding in binding_doc.get("bindings", []):
        if binding.get("source") == "principia":
            bound[binding["math_id"]].append(binding)

    obligations_file = ROOT / "verification" / "source_obligations.json"
    obligations = (json.loads(obligations_file.read_text(encoding="utf-8"))
                   .get("obligations", [])) if obligations_file.is_file() else []
    obligation_by_anchor: dict[str, list[str]] = defaultdict(list)
    for obligation in obligations:
        if obligation.get("latex_status") != "repaired":
            obligation_by_anchor[obligation["source_anchor"]].append(obligation["id"])

    claims = [n for n in atlas["nodes"]
              if n.get("type") in CLAIM_TYPES and n.get("book")]
    open_nodes = [n for n in claims if n["id"] not in maps]
    open_claims = []
    for node in open_nodes:
        bindings = bound.get(node["id"], [])
        open_claims.append({
            "id": node["id"],
            "name": node.get("name") or node["id"],
            "type": node["type"],
            "book": node["book"],
            "file": node.get("file"),
            "line": node.get("line"),
            "statement_sha": node.get("statement_sha"),
            "depends_on": node.get("depends_on") or [],
            "binding_count": len(bindings),
            "bound_declarations": sorted({b["declares"] for b in bindings}),
            "source_obligations": obligation_by_anchor.get(node["id"], []),
        })
    open_claims.sort(key=lambda x: (x["book"], x["line"] or 0, x["id"]))

    by_book: dict[str, list[dict]] = defaultdict(list)
    for claim in claims:
        by_book[claim["book"]].append(claim)
    books = []
    for book, nodes in by_book.items():
        mapped = sum(n["id"] in maps for n in nodes)
        books.append({"book": book, "claims": len(nodes), "mapped": mapped,
                      "open": len(nodes) - mapped})
    books.sort(key=lambda x: (-x["open"], x["book"]))

    all_bindings = binding_doc.get("bindings", [])
    attested = sum(bool(b.get("attested_in")) for b in all_bindings)
    packet = {
        "schema": "sketched.ps-lean-frontier.v1",
        "generated_from": {
            "principia_atlas": str(atlas_file),
            "coverage_maps": sorted(
                p.relative_to(ROOT).as_posix()
                for p in (ROOT / "verification").glob("*_lean_map.json")
            ),
            "bindings": "verification/bindings.json",
            "source_obligations": "verification/source_obligations.json",
        },
        "claims_total": len(claims),
        "mapped_total": len(claims) - len(open_nodes),
        "open_total": len(open_nodes),
        "source_obligations_unresolved": sum(
            o.get("latex_status") != "repaired" for o in obligations
        ),
        "binding_integrity": {
            "bindings_total": len(all_bindings),
            "human_attested": attested,
            "reserved": len(all_bindings) - attested,
        },
        "books": books,
        "open_claims": open_claims,
    }
    json_text = json.dumps(packet, indent=2) + "\n"
    md_text = render(packet)
    findings = []
    if args.check:
        if not OUT_JSON.is_file() or OUT_JSON.read_text(encoding="utf-8") != json_text:
            findings.append("verification/ps_frontier.json is stale")
        if not OUT_MD.is_file() or OUT_MD.read_text(encoding="utf-8") != md_text:
            findings.append("docs/22_PS_LEAN_FRONTIER.md is stale")
    else:
        OUT_JSON.write_text(json_text, encoding="utf-8")
        OUT_MD.write_text(md_text, encoding="utf-8")
    for finding in findings:
        print("[PS_FRONTIER] " + finding)
    print(f"{len(findings)} findings; {packet['mapped_total']}/{packet['claims_total']} "
          f"mapped; {packet['open_total']} exact frontier claims projected")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
