"""The whole-Principia-in-Lean work queue (ledger LPS-O5).

Groups the Principia atlas's claim-bearing nodes by book, counts how many
are already mapped to Lean declarations (via the book*_lean_map.json
coverage maps), and emits the priority queue sorted by open claim surface.
This is the program view: LPS-O5's "pick the next book by claim-surface
size", computed instead of asserted.

A queue, not an audit: it never judges coverage quality (that is the
coverage tool's job); it only measures how much of the atlas each map has
reached. Exit 1 only when the generated projections are stale (--check)
or inputs are malformed.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
QUEUE_JSON = ROOT / "verification" / "ps_queue.json"
DOC = ROOT / "docs" / "20_PS_LEAN_QUEUE.md"
SOURCE_OBLIGATIONS = ROOT / "verification" / "source_obligations.json"
CLAIM_TYPES = {"theorem", "proposition", "lemma", "corollary", "axiom"}


def atlas_path() -> Path | None:
    configured = os.environ.get("PRINCIPIA_ATLAS")
    candidates = [
        Path(configured) if configured else None,
        ROOT.parent / "principia" / "bib" / "principia_atlas.json",
        ROOT / "verification" / "principia_atlas.json",
    ]
    return next((p for p in candidates if p and p.is_file()), None)


def render_doc(packet: dict) -> str:
    lines = [
        "# Principia -> Lean program queue",
        "",
        "*Generated by verification/tools/ps_queue.py (ledger LPS-O5).*",
        "",
        "Claim-bearing atlas nodes (theorem/proposition/lemma/corollary/axiom) "
        "per book, against the Lean coverage maps. \"Mapped\" counts anchors a "
        "coverage map has reached at any class (proved-kernel, conditional, "
        "partial, definition); the coverage docs carry the per-anchor honesty. "
        "\"Bound\" counts anchors reached only by sha-pinned dual-source "
        "bindings (staleness-protected transcriptions awaiting a coverage map).",
        "",
        f"- Books with claim surface: **{packet['books_total']}**",
        f"- Claim-bearing nodes: **{packet['claims_total']}**",
        f"- Mapped: **{packet['mapped_total']}** "
        f"({packet['mapped_total']}/{packet['claims_total']})",
        f"- Unresolved source obligations: **{packet['source_obligations_unresolved']}** "+
        f"({packet['source_obligations_blocked']} downstream-blocking)",
        "",
        "| book | claims | mapped | bound | open | next |",
        "|---|---|---|---|---|---|",
    ]
    for row in packet["queue"]:
        lines.append(
            f"| {row['book']} | {row['claims']} | {row['mapped']} | "
            f"{row['bound']} | {row['open']} | {row['note']} |"
        )
    lines += [
        "",
        "The queue orders by open claim surface, descending: the top row is "
        "the next book the LPS-O5 program should enter. Poetry chapters carry "
        "no claim-bearing nodes and enter the program as carrier structure "
        "(see the ledger row), not through this queue.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    findings: list[str] = []

    src = atlas_path()
    if src is None:
        # external corpus absent (packet mode): skip, like the binding audit
        print("Principia atlas not found; skipping (external corpus not "
              "shipped in this packet)")
        return 0
    atlas = json.loads(src.read_text(encoding="utf-8"))

    mapped: set[str] = set()
    maps = sorted(ROOT.glob("verification/*_lean_map.json"))
    for mp in maps:
        doc = json.loads(mp.read_text(encoding="utf-8"))
        for entry in doc.get("entries", []):
            mapped.add(entry["atlas_id"])

    # anchors reached by sha-pinned dual-source bindings but not (yet) by a
    # coverage map — reached, with staleness protection, awaiting a map
    bound: set[str] = set()
    bindings_file = ROOT / "verification" / "bindings.json"
    if bindings_file.is_file():
        bdoc = json.loads(bindings_file.read_text(encoding="utf-8"))
        bound = {b["math_id"] for b in bdoc.get("bindings", [])
                 if b.get("source") == "principia"} - mapped

    by_book: dict[str, list[dict]] = {}
    for node in atlas["nodes"]:
        if node.get("type") in CLAIM_TYPES and node.get("book"):
            by_book.setdefault(node["book"], []).append(node)

    # definitions etc. are mappable but not claim-counted; only an anchor
    # absent from the atlas altogether is a finding
    all_ids = {n["id"] for n in atlas["nodes"] if "id" in n}
    unknown = mapped - all_ids
    if unknown:
        findings.append(f"mapped anchors absent from atlas: {sorted(unknown)}")

    rows = []
    for book, nodes in by_book.items():
        ids = {n["id"] for n in nodes}
        done = len(ids & mapped)
        nbound = len(ids & bound)
        open_ = len(ids) - done
        note = ("complete" if done == len(ids)
                else "in progress" if done > 0
                else "bound, unmapped" if nbound > 0 else "not started")
        rows.append({"book": book, "claims": len(ids), "mapped": done,
                     "bound": nbound, "open": open_, "note": note})
    rows.sort(key=lambda r: (-r["open"], r["book"]))

    source_obs = []
    if SOURCE_OBLIGATIONS.is_file():
        source_obs = json.loads(SOURCE_OBLIGATIONS.read_text(encoding="utf-8")).get("obligations", [])
    source_unresolved = sum(o.get("latex_status") != "repaired" for o in source_obs)
    source_blocked = sum(o.get("downstream_status") == "blocked" for o in source_obs)

    packet = {
        "schema": "sketched.ps-lean-queue.v1",
        "generated_from": {
            "principia_atlas": str(src),
            "coverage_maps": [m.relative_to(ROOT).as_posix() for m in maps],
        },
        "books_total": len(rows),
        "claims_total": sum(r["claims"] for r in rows),
        "mapped_total": sum(r["mapped"] for r in rows),
        "source_obligations_unresolved": source_unresolved,
        "source_obligations_blocked": source_blocked,
        "queue": rows,
    }
    queue_text = json.dumps(packet, indent=2) + "\n"
    doc_text = render_doc(packet)

    if args.check:
        if not QUEUE_JSON.is_file() or QUEUE_JSON.read_text(encoding="utf-8") != queue_text:
            findings.append("verification/ps_queue.json is stale")
        if not DOC.is_file() or DOC.read_text(encoding="utf-8") != doc_text:
            findings.append("docs/20_PS_LEAN_QUEUE.md is stale")
    else:
        QUEUE_JSON.write_text(queue_text, encoding="utf-8")
        DOC.write_text(doc_text, encoding="utf-8")

    for finding in findings:
        print("[PS_QUEUE] " + finding)
    top = rows[0]["book"] if rows else "none"
    print(f"{len(findings)} findings; {packet['mapped_total']}/"
          f"{packet['claims_total']} claim nodes mapped across "
          f"{len(rows)} books; next by open surface: {top}")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
