"""Audit Principia source-level obligations and generate their projection.

Coverage is deliberately not closure. Each obligation independently tracks
Lean evidence, LaTeX repair, and downstream discharge.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from atlas_extract import statement_sha

ROOT = Path(__file__).resolve().parents[2]
REGISTER = ROOT / "verification" / "source_obligations.json"
DOC = ROOT / "docs" / "21_PS_SOURCE_OBLIGATIONS.md"
FAILURE_MODES = {"missing_premise", "ill_typed", "counterexample", "interpretive_only", "missing_machinery"}
LEAN_STATUSES = {"exposed", "countermodel_proved", "conditional_kernel_proved", "positive_kernel_proved", "bridge_partially_proved", "typed_bridge_proved", "premise_packaged"}
LATEX_STATUSES = {"unresolved", "amendment_drafted", "repaired"}
DOWNSTREAM_STATUSES = {"blocked", "ready", "partially_discharged", "discharged"}
LAYERS = {"scholium", *(f"book{i}" for i in range(1, 10)), "appendix"}


def atlas_path() -> Path | None:
    configured = os.environ.get("PRINCIPIA_ATLAS")
    candidates = [
        Path(configured) if configured else None,
        ROOT.parent / "principia" / "bib" / "principia_atlas.json",
        ROOT / "verification" / "principia_atlas.json",
    ]
    return next((p for p in candidates if p and p.is_file()), None)


def render(data: dict, atlas: Path | None) -> str:
    obs = data["obligations"]
    lines = [
        "# Principia source obligations",
        "",
        "*Generated by `verification/tools/source_obligations.py` from",
        "`verification/source_obligations.json` — do not edit by hand.*",
        "",
        data["description"],
        "",
        f"- Open LaTeX obligations: **{sum(o['latex_status'] != 'repaired' for o in obs)}**",
        f"- Blocked downstream obligations: **{sum(o['downstream_status'] == 'blocked' for o in obs)}**",
        f"- Atlas: `{atlas}`" if atlas else "- Atlas: unavailable (anchor validation skipped)",
        "",
        "| id | source | failure | repair owner | Lean | LaTeX | downstream |",
        "|---|---|---|---|---|---|---|",
    ]
    for o in obs:
        lines.append(
            f"| {o['id']} | `{o['source_anchor']}` | {o['failure_mode']} | "
            f"{o['repair_owner']} | {o['lean_status']} | {o['latex_status']} | "
            f"{o['downstream_status']} |"
        )
    lines.append("")
    for o in obs:
        lines += [f"## {o['id']}: {o['source_anchor']}", "", o["summary"], ""]
        lines.append(f"- **Source:** `{o['source_file']}:{o['source_line']}` ({o['source_layer']})")
        lines.append(f"- **Source statement:** `{o['source_statement_sha']}`")
        lines.append(f"- **Repair owner:** {o['repair_owner']}")
        lines.append(f"- **Downstream consumers:** {', '.join(o['downstream_consumers'])}")
        lines.append(f"- **Required LaTeX repair:** {o['required_latex_repair']}")
        lines.append("- **Lean evidence:** " + ", ".join(
            f"`{e['declaration']}` ({e['kind']}; `{e['file']}`)" for e in o["lean_evidence"]
        ))
        lines.append(f"- **Lifecycle:** Lean `{o['lean_status']}`; LaTeX `{o['latex_status']}`; downstream `{o['downstream_status']}`")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    findings: list[tuple[str, str]] = []
    data = json.loads(REGISTER.read_text(encoding="utf-8"))
    obs = data.get("obligations", [])
    atlas_file = atlas_path()
    atlas_by_id: dict[str, dict] = {}
    if atlas_file:
        atlas = json.loads(atlas_file.read_text(encoding="utf-8"))
        atlas_by_id = {n["id"]: n for n in atlas["nodes"] if "id" in n}

    seen: set[str] = set()
    for o in obs:
        oid = o.get("id", "<missing>")
        if oid in seen:
            findings.append(("SRC_DUP_ID", oid))
        seen.add(oid)
        for key, allowed in (("failure_mode", FAILURE_MODES), ("lean_status", LEAN_STATUSES),
                             ("latex_status", LATEX_STATUSES), ("downstream_status", DOWNSTREAM_STATUSES)):
            if o.get(key) not in allowed:
                findings.append(("SRC_BAD_STATUS", f"{oid}: {key}={o.get(key)}"))
        if o.get("source_layer") not in LAYERS or o.get("repair_owner") not in LAYERS:
            findings.append(("SRC_BAD_LAYER", oid))
        if not o.get("downstream_consumers"):
            findings.append(("SRC_NO_CONSUMER", oid))
        for layer in o.get("downstream_consumers", []):
            if layer not in LAYERS:
                findings.append(("SRC_BAD_LAYER", f"{oid}: consumer={layer}"))
        node = atlas_by_id.get(o.get("source_anchor"))
        if atlas_file and node is None:
            findings.append(("SRC_BAD_ANCHOR", f"{oid}: {o.get('source_anchor')}"))
        elif node:
            if node.get("file") != o.get("source_file") or node.get("line") != o.get("source_line"):
                findings.append(("SRC_STALE_LOCATION", f"{oid}: atlas={node.get('file')}:{node.get('line')} register={o.get('source_file')}:{o.get('source_line')}"))
            current_sha = statement_sha(node.get("latex_body", ""))
            pinned_sha = o.get("source_statement_sha")
            if not pinned_sha:
                findings.append(("SRC_UNPINNED_STATEMENT", f"{oid}: {o.get('source_anchor')}"))
            elif pinned_sha != current_sha:
                findings.append(("SRC_STALE_STATEMENT", f"{oid}: atlas={current_sha} register={pinned_sha}"))
        evidence = o.get("lean_evidence", [])
        if not evidence:
            findings.append(("SRC_NO_EVIDENCE", oid))
        for e in evidence:
            path = ROOT / e.get("file", "")
            if not path.is_file():
                findings.append(("SRC_EVIDENCE_FILE", f"{oid}: {e.get('file')}"))
            elif e.get("declaration", "").split(".")[-1] not in path.read_text(encoding="utf-8"):
                findings.append(("SRC_EVIDENCE_DECL", f"{oid}: {e.get('declaration')}"))
        if not o.get("required_latex_repair", "").strip():
            findings.append(("SRC_NO_REPAIR", oid))

    projected = render(data, atlas_file) + "\n"
    if args.check:
        if not DOC.is_file() or DOC.read_text(encoding="utf-8") != projected:
            findings.append(("SRC_PROJECTION_STALE", str(DOC.relative_to(ROOT))))
    else:
        DOC.write_text(projected, encoding="utf-8", newline="\n")
    for code, msg in findings:
        print(f"[{code}] {msg}")
    print(f"{len(findings)} findings; {len(obs)} source obligations; projection -> {DOC.relative_to(ROOT)}")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())