/-
Site.lean — sieves, Grothendieck topologies on a refinement preorder,
the dense (double-negation) topology J_nn, the generated topology, and
the Site Bound lemma (lem:sitebound of forcing_correspondence_v15).

Mathlib-free: everything is built on core Lean 4.

Convention (matching the paper): `q ⊑ p` means "q refines p"; refinement
descends. A sieve on p is a refinement-closed subset of the cone below p.
-/

namespace ForcingKernel

/-- Refinement preorder. `q ⊑ p` : q refines p. -/
class Refines (P : Type u) where
  le : P → P → Prop
  refl : ∀ p, le p p
  trans : ∀ {p q r}, le p q → le q r → le p r

infix:50 " ⊑ " => Refines.le

variable {P : Type u} [Refines P]

open Refines

/-- A sieve on `p`: a refinement-closed collection of refinements of `p`. -/
structure Sieve (P : Type u) [Refines P] (p : P) where
  mem : P → Prop
  le_of_mem : ∀ {q}, mem q → q ⊑ p
  down : ∀ {q r}, mem q → r ⊑ q → mem r

/-- Sieves with the same members are equal (proof irrelevance). -/
theorem Sieve.ext {p : P} {S T : Sieve P p} (h : ∀ q, S.mem q ↔ T.mem q) : S = T := by
  have hm : S.mem = T.mem := funext fun q => propext (h q)
  cases S; cases T
  simp only [Sieve.mk.injEq]
  exact hm

/-- The maximal sieve on `p`: everything below `p`. -/
def Sieve.max (p : P) : Sieve P p where
  mem q := q ⊑ p
  le_of_mem h := h
  down h hr := trans hr h

/-- Pullback of a sieve on `p` along `q ⊑ p`. -/
def Sieve.pullback {p q : P} (h : q ⊑ p) (S : Sieve P p) : Sieve P q where
  mem r := r ⊑ q ∧ S.mem r
  le_of_mem hr := hr.1
  down hr hs := ⟨trans hs hr.1, S.down hr.2 hs⟩

/-- A Grothendieck topology on the refinement preorder, presented as a
covering predicate on sieves with the three standard axioms. -/
structure Topology (P : Type u) [Refines P] where
  covers : ∀ p : P, Sieve P p → Prop
  max_mem : ∀ p, covers p (Sieve.max p)
  pull : ∀ {p q} (h : q ⊑ p) (S : Sieve P p), covers p S → covers q (S.pullback h)
  trans : ∀ {p} (S : Sieve P p), covers p S → ∀ (R : Sieve P p),
    (∀ q (hq : S.mem q), covers q (R.pullback (S.le_of_mem hq))) → covers p R

/-- Supersieve monotonicity, derived from transitivity + maximality. -/
theorem Topology.mono (J : Topology P) {p : P} {S R : Sieve P p}
    (hcov : J.covers p S) (hsub : ∀ q, S.mem q → R.mem q) : J.covers p R := by
  apply J.trans S hcov R
  intro q hq
  have hRq : R.mem q := hsub q hq
  have hEq : R.pullback (S.le_of_mem hq) = Sieve.max q :=
    Sieve.ext fun r => ⟨fun h => h.1, fun h => ⟨h, R.down hRq h⟩⟩
  rw [hEq]
  exact J.max_mem q

/-- Order-density of a sieve below its object (the J_nn covering notion). -/
def denseBelow (p : P) (S : Sieve P p) : Prop :=
  ∀ q, q ⊑ p → ∃ r, r ⊑ q ∧ S.mem r

/-- The dense (double-negation) topology J_nn: covers are the dense sieves. -/
def Jnn (P : Type u) [Refines P] : Topology P where
  covers := denseBelow
  max_mem p q hq := ⟨q, refl q, hq⟩
  pull {p q} h S hS := fun r hrq =>
    match hS r (trans hrq h) with
    | ⟨s, hsr, hSs⟩ => ⟨s, hsr, trans hsr hrq, hSs⟩
  trans {p} S hS R hR := fun q hq =>
    match hS q hq with
    | ⟨s, hsq, hSs⟩ =>
      match hR s hSs s (refl s) with
      | ⟨r, hrs, hpb⟩ => ⟨r, trans hrs hsq, hpb.2⟩

/-- The covering relation generated by a family of designated sieves
(the finite analogue: `Dadm` generating `Jadm`). -/
inductive Gen (G : ∀ p : P, Sieve P p → Prop) : ∀ p : P, Sieve P p → Prop where
  | of {p : P} {S : Sieve P p} : G p S → Gen G p S
  | max (p : P) : Gen G p (Sieve.max p)
  | pull {p q : P} (h : q ⊑ p) (S : Sieve P p) : Gen G p S → Gen G q (S.pullback h)
  | trans {p : P} (S : Sieve P p) : Gen G p S → ∀ (R : Sieve P p),
      (∀ q (hq : S.mem q), Gen G q (R.pullback (S.le_of_mem hq))) → Gen G p R

/-- The generated topology `Jadm = ⟨B⟩` (Def. site of the paper). -/
def generated (G : ∀ p : P, Sieve P p → Prop) : Topology P where
  covers := Gen G
  max_mem := Gen.max
  pull h S hS := Gen.pull h S hS
  trans S hS R hR := Gen.trans S hS R hR

/-- The generated topology is least among topologies containing the
generators. -/
theorem generated_le (G : ∀ p : P, Sieve P p → Prop) (J : Topology P)
    (hG : ∀ p S, G p S → J.covers p S) :
    ∀ p S, (generated G).covers p S → J.covers p S := by
  intro p S h
  induction h with
  | of hg => exact hG _ _ hg
  | max p => exact J.max_mem p
  | pull h S _ ih => exact J.pull h S ih
  | trans S _ R _ ihS ihR => exact J.trans S ihS R ihR

/-- **Site Bound** (lem:sitebound): if every generator is dense, the
generated topology is contained in J_nn — every `Jadm`-cover is dense. -/
theorem site_bound (G : ∀ p : P, Sieve P p → Prop)
    (hdense : ∀ p S, G p S → denseBelow p S) :
    ∀ p S, (generated G).covers p S → denseBelow p S :=
  generated_le G (Jnn P) hdense

/-- Dense sieves are inhabited below their object; in particular no
`Jadm`-cover is empty when the generators are dense. -/
theorem denseBelow.nonempty {p : P} {S : Sieve P p} (h : denseBelow p S) :
    ∃ r, S.mem r :=
  match h p (refl p) with
  | ⟨r, _, hr⟩ => ⟨r, hr⟩

end ForcingKernel
