/-
ScholiumDynamics.lean — the scholium remainder's dynamics kernels:
flow, resolution cost, least action, linear reflexivity, and
paradox-triggered emergence.

Sources (Principia scholium, verbatim; sha-bound):

  definition:bk1_symbolic_flow / lemma:bk1_existence_and_uniqueness_of_flow —
    the flow generated by the drift field, existing and unique "by the
    fundamental theorem for flows." DISCRETE KERNEL: the orbit of a
    step map exists by construction and is the UNIQUE sequence
    satisfying the recurrence (`flow_unique`), with the flow semigroup
    law Φ_{m+n} = Φ_n ∘ Φ_m (`flow_semigroup`). The smooth ODE theorem
    stays open.
  definition:bk1_resolution_cost / definition:bk1_symbolic_distance —
    R(p,q) = inf over paths of accumulated cost. DISCRETE KERNEL: the
    path-infimum construction over an arbitrary nonneg symmetric step
    cost IS a pseudometric — nonneg, self-zero, symmetric (by path
    reversal), triangle (by path concatenation) — each law PROVED of
    the infimum, not assumed (`resCost_*`). Geodesics on Riemannian M
    stay open.
  lemma:bk1_completeness_of_symbolic_distance — completeness via
    Hopf–Rinow. FLOOR KERNEL: a metric with a positive separation
    floor is complete — every Cauchy sequence is eventually constant
    (`floor_complete`); the finite/discrete stand-in for geodesic
    completeness, honestly labeled.
  definition:bk1_symbolic_action_functional /
  theorem:bk1_princple_of_least_action — the Onsager–Machlup action
    L = ½(∂_s ρ − 𝓛ρ)². DISCRETE KERNEL, exact: the action is the
    accumulated squared evolution residual; it is nonnegative and
    VANISHES EXACTLY on Fokker–Planck trajectories
    (`least_action_iff_evolution`) — the dynamics are precisely the
    zero-action (least-action) paths. The MSR path integral stays
    open.
  definition:bk1_reflexive_update_map /
  proposition:bk1_limitation_linear_reflexive_maps — linear reflexive
    maps "cannot alter their own fixed point structure." KERNEL: every
    linear self-update fixes the origin (`linear_has_fixed_point`),
    its fixed-point set is closed under the linear structure
    (`linear_fixed_points_closed`), and no composition of linear
    updates ever escapes this (`linear_pipeline_fixes_zero`) — while a
    single affine (nonlinear) update has NO fixed point at all
    (`affine_escapes_fixed_points`). The self-representation clause of
    reflexivity is interpretive and stays open.
  definition:bk1_paradox_triggered_emergence /
  lemma:bk1_paradoxical_symmetry_breaking /
  lemma:bk1_contradiction_resolution_principle — a contradiction
    triggers emergence iff no in-frame reframing fixes it but an
    extension does; every such paradox is a symmetry that must break.
    KERNEL: a demanded distinction that every in-frame observable
    misses is unresolvable within the frame
    (`paradox_unresolvable_within`); the extension by one indicator
    observable resolves it (`extension_resolves` — the minimal
    extension of the resolution principle, constructive); and ANY
    resolving observable must break the swap symmetry that in-frame
    observables enjoyed (`resolution_breaks_symmetry`) — the
    symmetry-breaking lemma, exactly. Intensity budgets stay open.
-/

import Mathlib

namespace ForcingAnalysis.ScholiumDyn

/-! ### The discrete flow -/

variable {M : Type*}

/-- The orbit of the step map: the discrete symbolic flow. -/
def flowOrbit (d : M → M) (x : M) : ℕ → M := fun n => d^[n] x

/-- **Existence and uniqueness of the flow, discrete kernel**: the
orbit satisfies the recurrence, and ANY sequence satisfying it is the
orbit — genuine uniqueness, by induction. -/
theorem flow_unique (d : M → M) (x : M) (ρ : ℕ → M)
    (h0 : ρ 0 = x) (hs : ∀ n, ρ (n + 1) = d (ρ n)) :
    ρ = flowOrbit d x := by
  funext n
  induction n with
  | zero => simpa [flowOrbit] using h0
  | succ k ih =>
      rw [hs, ih]
      simp [flowOrbit, Function.iterate_succ_apply']

/-- The flow semigroup law: Φ_{m+n} = Φ_n ∘ Φ_m. -/
theorem flow_semigroup (d : M → M) (x : M) (m n : ℕ) :
    flowOrbit d x (m + n) = flowOrbit d (flowOrbit d x m) n := by
  simp only [flowOrbit]
  rw [add_comm, Function.iterate_add_apply]

/-! ### Resolution cost: the path-infimum pseudometric -/

variable (c : M → M → ℝ)

/-- Accumulated cost of a path from `p` through the listed waypoints
to `q`. -/
def pcost : M → List M → M → ℝ
  | p, [], q => c p q
  | p, a :: l, q => c p a + pcost a l q

variable {c}

theorem pcost_nonneg (hc0 : ∀ x y, 0 ≤ c x y) :
    ∀ (p : M) (l : List M) (q : M), 0 ≤ pcost c p l q := by
  intro p l
  induction l generalizing p with
  | nil => intro q; exact hc0 p q
  | cons a l ih =>
      intro q
      have := ih a q
      have := hc0 p a
      simp only [pcost]
      linarith [ih a q, hc0 p a]

/-- Concatenation splits the cost at the joint waypoint. -/
theorem pcost_append (p : M) (l₁ : List M) (a : M) (l₂ : List M) (q : M) :
    pcost c p (l₁ ++ a :: l₂) q = pcost c p l₁ a + pcost c a l₂ q := by
  induction l₁ generalizing p with
  | nil => simp [pcost]
  | cons b l ih =>
      simp only [List.cons_append, pcost, ih]
      ring

/-- Path reversal preserves cost, given a symmetric step cost. -/
theorem pcost_reverse (hsym : ∀ x y, c x y = c y x) :
    ∀ (p : M) (l : List M) (q : M), pcost c p l q = pcost c q l.reverse p := by
  intro p l
  induction l generalizing p with
  | nil => intro q; exact hsym p q
  | cons a l ih =>
      intro q
      simp only [pcost, List.reverse_cons]
      rw [ih a q, pcost_append (c := c) q l.reverse a [] p]
      simp only [pcost]
      rw [hsym p a]
      ring

/-- The resolution cost: the infimum of accumulated cost over all
paths (definition:bk1_resolution_cost, discrete form). -/
noncomputable def resCost (c : M → M → ℝ) (p q : M) : ℝ :=
  sInf (Set.range fun l : List M => pcost c p l q)

theorem resCost_set_nonempty (p q : M) :
    (Set.range fun l : List M => pcost c p l q).Nonempty :=
  ⟨pcost c p [] q, [], rfl⟩

theorem resCost_set_bddBelow (hc0 : ∀ x y, 0 ≤ c x y) (p q : M) :
    BddBelow (Set.range fun l : List M => pcost c p l q) := by
  refine ⟨0, fun r hr => ?_⟩
  obtain ⟨l, rfl⟩ := hr
  exact pcost_nonneg hc0 p l q

/-- The direct step bounds the resolution cost. -/
theorem resCost_le_step (hc0 : ∀ x y, 0 ≤ c x y) (p q : M) :
    resCost c p q ≤ c p q :=
  csInf_le (resCost_set_bddBelow hc0 p q) ⟨[], rfl⟩

theorem resCost_nonneg (hc0 : ∀ x y, 0 ≤ c x y) (p q : M) :
    0 ≤ resCost c p q :=
  le_csInf (resCost_set_nonempty p q) fun r hr => by
    obtain ⟨l, rfl⟩ := hr
    exact pcost_nonneg hc0 p l q

/-- Self-cost vanishes: the infimum meets the zero direct step. -/
theorem resCost_self (hc0 : ∀ x y, 0 ≤ c x y) (hcs : ∀ x, c x x = 0)
    (p : M) : resCost c p p = 0 :=
  le_antisymm (by simpa [hcs p] using resCost_le_step hc0 p p)
    (resCost_nonneg hc0 p p)

/-- **Symmetry of the resolution cost**, by path reversal: the two
path-cost ranges coincide as sets. -/
theorem resCost_symm (hsym : ∀ x y, c x y = c y x) (p q : M) :
    resCost c p q = resCost c q p := by
  unfold resCost
  congr 1
  ext r
  constructor
  · rintro ⟨l, rfl⟩
    exact ⟨l.reverse, (pcost_reverse hsym p l q).symm⟩
  · rintro ⟨l, rfl⟩
    exact ⟨l.reverse, (pcost_reverse hsym q l p).symm⟩

/-- **The triangle inequality for the resolution cost**, by path
concatenation through the waypoint — the infimum genuinely satisfies
the law, proved with the nested inf argument. -/
theorem resCost_triangle (hc0 : ∀ x y, 0 ≤ c x y) (p a q : M) :
    resCost c p q ≤ resCost c p a + resCost c a q := by
  have key : ∀ l₁ l₂ : List M,
      resCost c p q ≤ pcost c p l₁ a + pcost c a l₂ q := by
    intro l₁ l₂
    have hmem : pcost c p l₁ a + pcost c a l₂ q ∈
        Set.range fun l : List M => pcost c p l q :=
      ⟨l₁ ++ a :: l₂, pcost_append p l₁ a l₂ q⟩
    exact csInf_le (resCost_set_bddBelow hc0 p q) hmem
  have h2 : ∀ l₁ : List M,
      resCost c p q - pcost c p l₁ a ≤ resCost c a q := by
    intro l₁
    refine le_csInf (resCost_set_nonempty a q) fun r hr => ?_
    obtain ⟨l₂, rfl⟩ := hr
    linarith [key l₁ l₂]
  have h3 : resCost c p q - resCost c a q ≤ resCost c p a := by
    refine le_csInf (resCost_set_nonempty p a) fun r hr => ?_
    obtain ⟨l₁, rfl⟩ := hr
    linarith [h2 l₁]
  linarith

/-- **Floor completeness** (the finite stand-in for Hopf–Rinow): a
distance with a positive separation floor is complete — every Cauchy
sequence is eventually constant, hence convergent. Geodesic
completeness on Riemannian M stays open. -/
theorem floor_complete (d : M → M → ℝ) {floor : ℝ} (hf : 0 < floor)
    (hd : ∀ x y, x ≠ y → floor ≤ d x y) (u : ℕ → M)
    (hC : ∀ ε > 0, ∃ N, ∀ m ≥ N, ∀ n ≥ N, d (u m) (u n) < ε) :
    ∃ N, ∀ n ≥ N, u n = u N := by
  obtain ⟨N, hN⟩ := hC floor hf
  refine ⟨N, fun n hn => ?_⟩
  by_contra hne
  exact absurd (hN n hn N (le_refl N)) (not_lt.mpr (hd _ _ hne))

/-! ### The discrete least-action principle -/

variable {k : ℕ}

/-- The discrete Onsager–Machlup action: accumulated squared evolution
residual of a density path against the evolution operator
(definition:bk1_symbolic_action_functional, discrete form). -/
def action (step : (Fin k → ℝ) → (Fin k → ℝ)) (ρ : ℕ → Fin k → ℝ)
    (T : ℕ) : ℝ :=
  ∑ s ∈ Finset.range T, ∑ i, (ρ (s + 1) i - step (ρ s) i) ^ 2

theorem action_nonneg (step : (Fin k → ℝ) → (Fin k → ℝ))
    (ρ : ℕ → Fin k → ℝ) (T : ℕ) : 0 ≤ action step ρ T :=
  Finset.sum_nonneg fun _ _ =>
    Finset.sum_nonneg fun _ _ => sq_nonneg _

/-- **The principle of least action, discrete and exact**
(theorem:bk1_princple_of_least_action): the action vanishes exactly on
evolution trajectories — the Fokker–Planck dynamics ARE the zero-action
(least-action) paths, and zero is the global minimum by
`action_nonneg`. The MSR path-integral formulation stays open. -/
theorem least_action_iff_evolution (step : (Fin k → ℝ) → (Fin k → ℝ))
    (ρ : ℕ → Fin k → ℝ) (T : ℕ) :
    action step ρ T = 0 ↔ ∀ s < T, ρ (s + 1) = step (ρ s) := by
  unfold action
  rw [Finset.sum_eq_zero_iff_of_nonneg
    (fun s _ => Finset.sum_nonneg fun i _ => sq_nonneg _)]
  constructor
  · intro h s hs
    funext i
    have hrow := h s (Finset.mem_range.mpr hs)
    have hterm := (Finset.sum_eq_zero_iff_of_nonneg
      (fun i _ => sq_nonneg _)).mp hrow i (Finset.mem_univ i)
    have := pow_eq_zero_iff (n := 2) (by norm_num) |>.mp hterm
    linarith [sub_eq_zero.mp this]
  · intro h s hs
    rw [h s (Finset.mem_range.mp hs)]
    simp

/-! ### Local stability at a reflective fixed locus -/

/-- The scalar kernel of the Scholium's combined symbolic dynamics:
reflection displacement plus positively weighted drift. -/
def combinedFlow (R D : ℝ → ℝ) (α x : ℝ) : ℝ :=
  (R x - x) + α * D x

/-- A state is an equilibrium when the combined flow vanishes. -/
def IsCombinedEquilibrium (R D : ℝ → ℝ) (α x : ℝ) : Prop :=
  combinedFlow R D α x = 0

/-- The valid direction of the Scholium's equilibrium clause: a reflective
fixed point with zero drift is always an equilibrium. -/
theorem equilibrium_of_fixed_and_drift_zero
    (R D : ℝ → ℝ) (α x : ℝ) (hR : R x = x) (hD : D x = 0) :
    IsCombinedEquilibrium R D α x := by
  simp [IsCombinedEquilibrium, combinedFlow, hR, hD]

/-- Idempotence and positive drift weight do not justify the converse:
reflection displacement can cancel nonzero drift. This countermodel uses the
idempotent constant stabilizer, so it respects the source lemma's stated
structural hypothesis. -/
theorem equilibrium_cancellation_counterexample :
    let R : ℝ → ℝ := fun _ => 1
    let D : ℝ → ℝ := fun _ => -1
    (∀ x, R (R x) = R x) ∧
      IsCombinedEquilibrium R D 1 0 ∧ R 0 ≠ 0 ∧ D 0 ≠ 0 := by
  norm_num [IsCombinedEquilibrium, combinedFlow]

/-- The missing hypothesis can be stated as component alignment: reflection
displacement and drift point to the same closed half-line, so they cannot
cancel one another. -/
def ComponentsAlignedAt (R D : ℝ → ℝ) (x : ℝ) : Prop :=
  (0 ≤ R x - x ∧ 0 ≤ D x) ∨ (R x - x ≤ 0 ∧ D x ≤ 0)

/-- Under positive weighting and explicit noncancellation, the Scholium's
claimed equilibrium iff is recovered exactly. This is the safe upstream
contract for Book 4 staging and Book 7 reflective stability. -/
theorem equilibrium_iff_fixed_and_drift_zero_of_aligned
    (R D : ℝ → ℝ) {α x : ℝ} (hα : 0 < α)
    (halign : ComponentsAlignedAt R D x) :
    IsCombinedEquilibrium R D α x ↔ R x = x ∧ D x = 0 := by
  constructor
  · intro heq
    unfold IsCombinedEquilibrium combinedFlow at heq
    rcases halign with hpos | hneg
    · have hαD : 0 ≤ α * D x := mul_nonneg hα.le hpos.2
      have hdisp : R x - x = 0 := by linarith
      have hdrift : D x = 0 := by nlinarith
      exact ⟨sub_eq_zero.mp hdisp, hdrift⟩
    · have hαD : α * D x ≤ 0 := mul_nonpos_of_nonneg_of_nonpos hα.le hneg.2
      have hdisp : R x - x = 0 := by linarith
      have hdrift : D x = 0 := by nlinarith
      exact ⟨sub_eq_zero.mp hdisp, hdrift⟩
  · rintro ⟨hR, hD⟩
    exact equilibrium_of_fixed_and_drift_zero R D α x hR hD

/-! ### History-bearing reflective state and the arrow of time -/

/-- A reflective state carries both its visible coordinate and the number of
recorded differentiation traces. Equality of visible coordinates alone is
therefore not equality of states. -/
structure ReflectiveState (X : Type*) where
  base : X
  traces : ℕ

/-- One discrete combined-flow step together with its trace production.
The visible coordinate follows the Euler step; history records are appended
rather than subtracted, expressing the observer-relative temporal direction. -/
def recordedCombinedStep (R D : ℝ → ℝ) (α : ℝ) (newTraces : ℕ)
    (s : ReflectiveState ℝ) : ReflectiveState ℝ where
  base := s.base + combinedFlow R D α s.base
  traces := s.traces + newTraces

/-- Full-state stationarity is exactly the conjunction the scalar equation
was missing: zero visible combined flow and zero new trace production. -/
theorem recordedCombinedStep_eq_iff
    (R D : ℝ → ℝ) (α : ℝ) (newTraces : ℕ) (s : ReflectiveState ℝ) :
    recordedCombinedStep R D α newTraces s = s ↔
      IsCombinedEquilibrium R D α s.base ∧ newTraces = 0 := by
  constructor
  · intro h
    have hbase := congrArg ReflectiveState.base h
    have htraces := congrArg ReflectiveState.traces h
    constructor
    · unfold recordedCombinedStep at hbase
      simp only at hbase
      unfold IsCombinedEquilibrium
      linarith
    · unfold recordedCombinedStep at htraces
      simp only at htraces
      omega
  · rintro ⟨hflow, rfl⟩
    rcases s with ⟨base, traces⟩
    simp [recordedCombinedStep, IsCombinedEquilibrium] at hflow ⊢
    exact hflow

/-- A zero visible displacement can coexist with strict temporal advance,
but it cannot masquerade as equilibrium of the history-bearing state. -/
theorem base_cancellation_not_full_equilibrium
    (R D : ℝ → ℝ) (α : ℝ) {newTraces : ℕ} (htrace : 0 < newTraces)
    (s : ReflectiveState ℝ) (hflow : IsCombinedEquilibrium R D α s.base) :
    (recordedCombinedStep R D α newTraces s).base = s.base ∧
      recordedCombinedStep R D α newTraces s ≠ s := by
  constructor
  · simp [recordedCombinedStep, IsCombinedEquilibrium] at hflow ⊢
    exact hflow
  · intro h
    have := (recordedCombinedStep_eq_iff R D α newTraces s).mp h
    omega

/-- Positive trace production alone rules out a fixed full state, regardless
of whether reflection and drift cancel in the visible projection. -/
theorem no_full_equilibrium_of_trace_production
    (R D : ℝ → ℝ) (α : ℝ) {newTraces : ℕ} (htrace : 0 < newTraces)
    (s : ReflectiveState ℝ) :
    recordedCombinedStep R D α newTraces s ≠ s := by
  intro h
  have := (recordedCombinedStep_eq_iff R D α newTraces s).mp h
  omega

/-! ### Linear projection and reflective tangent splitting -/

variable {W : Type*} [AddCommGroup W] [Module ℝ W]

/-- At a fixed point of a differentiable idempotent stabilizer, the
Frechet derivative is itself idempotent. This is the analytic chain-rule
bridge from reflection to the linear projection used below. -/
theorem hasFDerivAt_idempotent_at_fixed
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R : E → E) (P : E →L[ℝ] E) (x : E)
    (hfix : R x = x) (hidempotent : ∀ y, R (R y) = R y)
    (hderiv : HasFDerivAt R P x) :
    P.comp P = P := by
  have houter : HasFDerivAt R P (R x) := by
    simpa [hfix] using hderiv
  have hcomp : HasFDerivAt (R ∘ R) (P.comp P) x :=
    houter.comp x hderiv
  have hevent : R =ᶠ[nhds x] (R ∘ R) :=
    Filter.Eventually.of_forall fun y => (hidempotent y).symm
  have hcompR : HasFDerivAt R (P.comp P) x :=
    hcomp.congr_of_eventuallyEq hevent
  exact hcompR.unique hderiv

/-- The honest algebraic datum behind the differential
`P = dR_stab,x*`: a linear map whose square is itself. -/
structure ReflectiveLinearProjection (W : Type*) [AddCommGroup W] [Module ℝ W] where
  P : W →ₗ[ℝ] W
  idempotent : P.comp P = P

namespace ReflectiveLinearProjection

theorem apply_apply (Q : ReflectiveLinearProjection W) (x : W) :
    Q.P (Q.P x) = Q.P x := by
  have h := congrArg (fun f : W →ₗ[ℝ] W => f x) Q.idempotent
  simpa using h

/-- Every tangent vector decomposes into its projected component and its
transverse residual. -/
theorem exists_image_kernel_decomposition
    (Q : ReflectiveLinearProjection W) (x : W) :
    ∃ y z, x = y + z ∧ Q.P y = y ∧ Q.P z = 0 := by
  refine ⟨Q.P x, x - Q.P x, by abel, Q.apply_apply x, ?_⟩
  rw [map_sub, Q.apply_apply]
  simp

/-- The image and kernel meet only at zero, so the decomposition is a genuine
splitting rather than two overlapping descriptions. -/
theorem image_kernel_intersection_zero
    (Q : ReflectiveLinearProjection W) {y : W}
    (himage : ∃ x, Q.P x = y) (hkernel : Q.P y = 0) : y = 0 := by
  rcases himage with ⟨x, rfl⟩
  rw [Q.apply_apply] at hkernel
  exact hkernel

/-- On the projected/image directions, the unperturbed linearization
`P - I` vanishes. -/
theorem sub_identity_on_image
    (Q : ReflectiveLinearProjection W) (x : W) :
    Q.P (Q.P x) - Q.P x = 0 := by
  rw [Q.apply_apply]
  simp

/-- On transverse/kernel directions, the same unperturbed linearization acts
as negative identity. -/
theorem sub_identity_on_kernel
    (Q : ReflectiveLinearProjection W) {z : W} (hz : Q.P z = 0) :
    Q.P z - z = -z := by
  rw [hz]
  simp

/-- Package the derivative of a differentiable idempotent stabilizer as the
reflective projection, deriving rather than repeating its idempotence law. -/
noncomputable def ofHasFDerivAt
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R : E → E) (P : E →L[ℝ] E) (x : E)
    (hfix : R x = x) (hidempotent : ∀ y, R (R y) = R y)
    (hderiv : HasFDerivAt R P x) :
    ReflectiveLinearProjection E where
  P := P.toLinearMap
  idempotent := by
    have hp := hasFDerivAt_idempotent_at_fixed R P x hfix hidempotent hderiv
    ext y
    have hy := congrArg (fun L : E →L[ℝ] E => L y) hp
    simpa using hy

/-- Therefore the tangent-space image/kernel decomposition follows directly
from the analytic idempotent stabilizer hypotheses. -/
theorem derivative_image_kernel_decomposition
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R : E → E) (P : E →L[ℝ] E) (x v : E)
    (hfix : R x = x) (hidempotent : ∀ y, R (R y) = R y)
    (hderiv : HasFDerivAt R P x) :
    ∃ y z, v = y + z ∧ P y = y ∧ P z = 0 :=
  (ofHasFDerivAt R P x hfix hidempotent hderiv).exists_image_kernel_decomposition v

end ReflectiveLinearProjection

/-! ### The complete reflective-drift Jacobian -/

/-- The normed-space combined dynamics from the Scholium:
reflective displacement plus weighted drift. -/
def combinedVectorField
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R D : E → E) (α : ℝ) (x : E) : E :=
  R x - x + α • D x

/-- The complete linearization `J = (P - I) + α dD`. -/
def combinedJacobian
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) : E →L[ℝ] E :=
  (P - ContinuousLinearMap.id ℝ E) + α • A

@[simp] theorem combinedJacobian_apply
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (v : E) :
    combinedJacobian P A α v = P v - v + α • A v := by
  simp [combinedJacobian]

/-- The derivative rules genuinely derive the complete Jacobian formula. -/
theorem hasFDerivAt_combinedVectorField
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R D : E → E) (P A : E →L[ℝ] E) (α : ℝ) (x : E)
    (hR : HasFDerivAt R P x) (hD : HasFDerivAt D A x) :
    HasFDerivAt (combinedVectorField R D α) (combinedJacobian P A α) x := by
  have hreflect := hR.sub (hasFDerivAt_id x)
  have hdrift := hD.const_smul α
  convert hreflect.add hdrift using 1 <;> rfl

/-- At a fixed point of an idempotent differentiable stabilizer, the same
hypotheses simultaneously derive the complete Jacobian and its projection
law. -/
theorem completeJacobian_at_reflective_fixed
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R D : E → E) (P A : E →L[ℝ] E) (α : ℝ) (x : E)
    (hfix : R x = x) (hidempotent : ∀ y, R (R y) = R y)
    (hR : HasFDerivAt R P x) (hD : HasFDerivAt D A x) :
    HasFDerivAt (combinedVectorField R D α) (combinedJacobian P A α) x ∧
      P.comp P = P :=
  ⟨hasFDerivAt_combinedVectorField R D P A α x hR hD,
    hasFDerivAt_idempotent_at_fixed R P x hfix hidempotent hR⟩

/-- On projected/tangential directions the reflective term vanishes, leaving
the drift derivative exactly. -/
theorem combinedJacobian_on_image
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) {v : E} (hv : P v = v) :
    combinedJacobian P A α v = α • A v := by
  simp [combinedJacobian_apply, hv]

/-- On transverse/kernel directions the complete Jacobian is negative
identity plus the drift derivative. -/
theorem combinedJacobian_on_kernel
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) {v : E} (hv : P v = 0) :
    combinedJacobian P A α v = -v + α • A v := by
  simp [combinedJacobian_apply, hv]

/-! ### Fixed-locus tangents and transverse stability -/

/-- A vector is tangent to the fixed locus when it is the velocity of a
differentiable curve through the point which remains fixed by `R`.  This
curve-based definition avoids assuming a manifold structure on the locus. -/
def IsFixedLocusVelocity
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R : E → E) (x v : E) : Prop :=
  ∃ γ : ℝ → E, γ 0 = x ∧ (∀ t, R (γ t) = γ t) ∧ HasDerivAt γ v 0

/-- For a differentiable idempotent retraction, the fixed-locus velocities
are exactly the image directions of its derivative.  The reverse implication
is constructive: project the affine line `x + t • v` back onto the locus. -/
theorem fixedLocusVelocity_iff_derivative_fixed
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (R : E → E) (P : E →L[ℝ] E) (x v : E)
    (hfix : R x = x) (hidempotent : ∀ y, R (R y) = R y)
    (hR : HasFDerivAt R P x) :
    IsFixedLocusVelocity R x v ↔ P v = v := by
  constructor
  · rintro ⟨γ, hγ0, hγfix, hγ⟩
    have hR0 : HasFDerivAt R P (γ 0) := by simpa [hγ0] using hR
    have hcomp : HasDerivAt (fun t => R (γ t)) (P v) 0 := by
      exact hR0.comp_hasDerivAt 0 hγ
    have heq : (fun t => R (γ t)) = γ := funext hγfix
    rw [heq] at hcomp
    exact hγ.unique hcomp |>.symm
  · intro hv
    let line : ℝ → E := fun t => x + t • v
    have hline : HasDerivAt line v 0 := by
      have hadd := (hasDerivAt_const (x := (0 : ℝ)) x).add
        ((hasDerivAt_id (0 : ℝ)).smul_const v)
      convert hadd using 1
      · ext t
        simp [line]
      · simp
    refine ⟨fun t => R (line t), ?_, fun t => hidempotent (line t), ?_⟩
    · simp [line, hfix]
    · have hR0 : HasFDerivAt R P (line 0) := by simpa [line] using hR
      change HasDerivAt (R ∘ line) v 0
      simpa only [hv] using hR0.comp_hasDerivAt 0 hline

/-- One explicit Euler step of the complete linearized dynamics. -/
def combinedEulerLinearization
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) : E →L[ℝ] E :=
  ContinuousLinearMap.id ℝ E + combinedJacobian P A α

/-- On transverse directions the Euler identity cancels the reflective
negative identity exactly; only the differentiated drift remains. -/
theorem combinedEulerLinearization_on_kernel
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) {v : E} (hv : P v = 0) :
    combinedEulerLinearization P A α v = α • A v := by
  simp [combinedEulerLinearization, combinedJacobian_on_kernel P A α hv]

/-- Quantitative transverse bound for the complete Euler linearization. -/
theorem norm_combinedEulerLinearization_on_kernel_le
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) {v : E} (hv : P v = 0) :
    ‖combinedEulerLinearization P A α v‖ ≤ |α| * ‖A‖ * ‖v‖ := by
  rw [combinedEulerLinearization_on_kernel P A α hv, norm_smul, Real.norm_eq_abs]
  calc
    |α| * ‖A v‖ ≤ |α| * (‖A‖ * ‖v‖) :=
      mul_le_mul_of_nonneg_left (A.le_opNorm v) (abs_nonneg α)
    _ = |α| * ‖A‖ * ‖v‖ := by ring

/-- If the drift perturbation is smaller than the unit reflective margin,
every nonzero transverse vector strictly contracts in one linearized step. -/
theorem combinedEulerLinearization_transverse_contracts
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (hsmall : |α| * ‖A‖ < 1)
    {v : E} (hv : P v = 0) (hv0 : v ≠ 0) :
    ‖combinedEulerLinearization P A α v‖ < ‖v‖ := by
  calc
    ‖combinedEulerLinearization P A α v‖ ≤ |α| * ‖A‖ * ‖v‖ :=
      norm_combinedEulerLinearization_on_kernel_le P A α hv
    _ < 1 * ‖v‖ := mul_lt_mul_of_pos_right hsmall (norm_pos_iff.mpr hv0)
    _ = ‖v‖ := one_mul _

/-- The drift derivative respects the transverse bundle selected by P. -/
def PreservesTransverseKernel
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) : Prop :=
  ∀ ⦃v : E⦄, P v = 0 → P (A v) = 0

/-- Kernel invariance propagates through one complete Euler step. -/
theorem combinedEulerLinearization_preserves_kernel
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (hinv : PreservesTransverseKernel P A)
    {v : E} (hv : P v = 0) :
    P (combinedEulerLinearization P A α v) = 0 := by
  rw [combinedEulerLinearization_on_kernel P A α hv, map_smul]
  rw [hinv hv, smul_zero]

/-- Every iterate remains transverse when the differentiated drift preserves
the transverse kernel. -/
theorem combinedEulerLinearization_iterate_mem_kernel
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (hinv : PreservesTransverseKernel P A)
    {v : E} (hv : P v = 0) :
    ∀ n, P ((combinedEulerLinearization P A α)^[n] v) = 0 := by
  intro n
  induction n with
  | zero => simpa using hv
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      exact combinedEulerLinearization_preserves_kernel P A α hinv ih

/-- The full transverse orbit obeys the geometric envelope
(|α| * ‖A‖)^n * ‖v‖. -/
theorem norm_combinedEulerLinearization_iterate_le
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (hinv : PreservesTransverseKernel P A)
    {v : E} (hv : P v = 0) :
    ∀ n, ‖(combinedEulerLinearization P A α)^[n] v‖ ≤
      (|α| * ‖A‖) ^ n * ‖v‖ := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      calc
        ‖combinedEulerLinearization P A α
            ((combinedEulerLinearization P A α)^[n] v)‖
            ≤ (|α| * ‖A‖) *
                ‖(combinedEulerLinearization P A α)^[n] v‖ :=
          norm_combinedEulerLinearization_on_kernel_le P A α
            (combinedEulerLinearization_iterate_mem_kernel P A α hinv hv n)
        _ ≤ (|α| * ‖A‖) * ((|α| * ‖A‖) ^ n * ‖v‖) :=
          mul_le_mul_of_nonneg_left ih
            (mul_nonneg (abs_nonneg α) (norm_nonneg A))
        _ = (|α| * ‖A‖) ^ (n + 1) * ‖v‖ := by ring

/-- Under invariant transverse drift and the strict unit margin, the complete
linearized transverse dynamics converge geometrically to zero. -/
theorem combinedEulerLinearization_iterate_tendsto_zero
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α : ℝ) (hinv : PreservesTransverseKernel P A)
    (hsmall : |α| * ‖A‖ < 1) {v : E} (hv : P v = 0) :
    Filter.Tendsto (fun n => (combinedEulerLinearization P A α)^[n] v)
      Filter.atTop (nhds 0) := by
  rw [tendsto_zero_iff_norm_tendsto_zero]
  have hq0 : 0 ≤ |α| * ‖A‖ :=
    mul_nonneg (abs_nonneg α) (norm_nonneg A)
  have hpow : Filter.Tendsto (fun n : ℕ => (|α| * ‖A‖) ^ n)
      Filter.atTop (nhds 0) :=
    tendsto_pow_atTop_nhds_zero_of_abs_lt_one
      (by rw [abs_of_nonneg hq0]; exact hsmall)
  have henvelope : Filter.Tendsto
      (fun n : ℕ => (|α| * ‖A‖) ^ n * ‖v‖)
      Filter.atTop (nhds 0) := by
    simpa using hpow.mul_const ‖v‖
  exact squeeze_zero (fun _ => norm_nonneg _)
    (norm_combinedEulerLinearization_iterate_le P A α hinv hv) henvelope

/-! ### Transverse eigenvalue disk -/

/-- Every real eigenvalue carried by a nonzero transverse eigenvector lies in
the closed disk determined by the perturbation factor. -/
theorem transverse_eigenvalue_abs_le
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α μ : ℝ) {v : E}
    (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedEulerLinearization P A α v = μ • v) :
    |μ| ≤ |α| * ‖A‖ := by
  have hbound := norm_combinedEulerLinearization_on_kernel_le P A α hv
  rw [heigen, norm_smul, Real.norm_eq_abs] at hbound
  nlinarith [norm_pos_iff.mpr hv0]

/-- Below the strict reflective margin, every real transverse eigenvalue lies
strictly inside the unit disk. -/
theorem transverse_eigenvalue_abs_lt_one
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α μ : ℝ) (hsmall : |α| * ‖A‖ < 1)
    {v : E} (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedEulerLinearization P A α v = μ • v) :
    |μ| < 1 :=
  lt_of_le_of_lt
    (transverse_eigenvalue_abs_le P A α μ hv hv0 heigen) hsmall

/-- Consequently no nonzero transverse eigenmode can be neutral or unstable
when the perturbation factor is below one. -/
theorem no_transverse_unstable_eigenmode
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α μ : ℝ) (hsmall : |α| * ‖A‖ < 1) :
    ¬ ∃ v : E, P v = 0 ∧ v ≠ 0 ∧
      combinedEulerLinearization P A α v = μ • v ∧ 1 ≤ |μ| := by
  rintro ⟨v, hv, hv0, heigen, hunstable⟩
  have hstable :=
    transverse_eigenvalue_abs_lt_one P A α μ hsmall hv hv0 heigen
  exact (not_lt_of_ge hunstable) hstable

/-! ### Complete-Jacobian operator semigroup -/

/-- The full bounded-operator exponential generated by the complete
Jacobian. Completeness makes the continuous endomorphisms a Banach algebra,
so the exponential is defined by its convergent power series. -/
noncomputable def jacobianSemigroup
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α t : ℝ) : E →L[ℝ] E :=
  NormedSpace.exp (t • combinedJacobian P A α)

/-- The operator exponential starts at the identity. -/
@[simp] theorem jacobianSemigroup_zero
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α : ℝ) :
    jacobianSemigroup P A α 0 = ContinuousLinearMap.id ℝ E := by
  simp [jacobianSemigroup]
  rfl

/-- The complete-Jacobian exponential is a one-parameter semigroup. -/
theorem jacobianSemigroup_add
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α s t : ℝ) :
    jacobianSemigroup P A α (s + t) =
      jacobianSemigroup P A α s * jacobianSemigroup P A α t := by
  unfold jacobianSemigroup
  rw [add_smul]
  exact NormedSpace.exp_add_of_commute_of_mem_ball
    (((Commute.refl (combinedJacobian P A α)).smul_left s).smul_right t)
    ((NormedSpace.expSeries_radius_eq_top ℝ (E →L[ℝ] E)).symm ▸
      edist_lt_top _ _)
    ((NormedSpace.expSeries_radius_eq_top ℝ (E →L[ℝ] E)).symm ▸
      edist_lt_top _ _)

/-- Pointwise, the semigroup law is composition of time evolution. -/
theorem jacobianSemigroup_add_apply
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α s t : ℝ) (v : E) :
    jacobianSemigroup P A α (s + t) v =
      jacobianSemigroup P A α s (jacobianSemigroup P A α t v) := by
  rw [jacobianSemigroup_add]
  rfl

/-- The operator-valued semigroup solves the autonomous linearized equation:
its derivative is the semigroup operator multiplied by the Jacobian. -/
theorem hasDerivAt_jacobianSemigroup
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α t : ℝ) :
    HasDerivAt (jacobianSemigroup P A α)
      (jacobianSemigroup P A α t * combinedJacobian P A α) t := by
  unfold jacobianSemigroup
  exact hasDerivAt_exp_smul_const (combinedJacobian P A α) t

/-! ### Semigroup action on eigenmodes -/

/-- Powers of a continuous endomorphism act by scalar powers on an
eigenvector. -/
theorem continuousLinearMap_pow_apply_eigen
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (J : E →L[ℝ] E) (ν : ℝ) {v : E} (heigen : J v = ν • v) :
    ∀ n, (J ^ n) v = (ν ^ n) • v := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ]
      change (J ^ n) (J v) = _
      rw [heigen, map_smul, ih, pow_succ]
      simp only [smul_smul]
      rw [mul_comm]

/-- The full operator exponential acts on a Jacobian eigenvector by the
corresponding scalar exponential. -/
theorem jacobianSemigroup_apply_eigen
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α ν t : ℝ) {v : E}
    (heigen : combinedJacobian P A α v = ν • v) :
    jacobianSemigroup P A α t v = Real.exp (t * ν) • v := by
  let J := combinedJacobian P A α
  have htJ : (t • J) v = (t * ν) • v := by
    rw [smul_apply, heigen, smul_smul]
  have hsum : Summable
      (fun n : ℕ => ((n.factorial : ℝ)⁻¹) • (t • J) ^ n) :=
    NormedSpace.expSeries_summable' (𝕂 := ℝ) (t • J)
  have hscalar : Summable
      (fun n : ℕ => ((n.factorial : ℝ)⁻¹) • (t * ν) ^ n) :=
    NormedSpace.expSeries_summable' (𝕂 := ℝ) (t * ν)
  unfold jacobianSemigroup
  change NormedSpace.exp (t • J) v = _
  rw [congrFun (NormedSpace.exp_eq_tsum ℝ) (t • J)]
  change (ContinuousLinearMap.apply ℝ E v)
      (∑' n : ℕ, ((n.factorial : ℝ)⁻¹) • (t • J) ^ n) = _
  rw [(ContinuousLinearMap.apply ℝ E v).map_tsum hsum]
  rw [Real.exp_eq_exp_ℝ, congrFun (NormedSpace.exp_eq_tsum ℝ) (t * ν)]
  rw [← hscalar.tsum_smul_const v]
  apply tsum_congr
  intro n
  simp only [ContinuousLinearMap.apply_apply, smul_apply]
  rw [continuousLinearMap_pow_apply_eigen (t • J) (t * ν) htJ n]
  rw [smul_smul]
  simp [smul_eq_mul]

/-! ### Continuous-time transverse eigenmodes -/

/-- A Jacobian eigenmode has Euler eigenvalue shifted by one. -/
theorem combinedEulerLinearization_eigen_of_jacobian_eigen
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α ν : ℝ) {v : E}
    (heigen : combinedJacobian P A α v = ν • v) :
    combinedEulerLinearization P A α v = (1 + ν) • v := by
  rw [combinedEulerLinearization]
  simp only [add_apply, ContinuousLinearMap.id_apply, heigen]
  rw [add_smul, one_smul]

/-- A transverse Jacobian eigenvalue is bounded above by the negative
stability margin -(1 - |α| * ‖A‖). -/
theorem transverse_jacobian_eigenvalue_le_negative_margin
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α ν : ℝ) {v : E}
    (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedJacobian P A α v = ν • v) :
    ν ≤ -(1 - |α| * ‖A‖) := by
  have hdisk := transverse_eigenvalue_abs_le P A α (1 + ν) hv hv0
    (combinedEulerLinearization_eigen_of_jacobian_eigen P A α ν heigen)
  have hle : 1 + ν ≤ |1 + ν| := le_abs_self (1 + ν)
  linarith

/-- Below the strict perturbation margin every real transverse Jacobian
eigenvalue is strictly negative. -/
theorem transverse_jacobian_eigenvalue_neg
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α ν : ℝ) (hsmall : |α| * ‖A‖ < 1)
    {v : E} (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedJacobian P A α v = ν • v) :
    ν < 0 := by
  have hmargin :=
    transverse_jacobian_eigenvalue_le_negative_margin
      P A α ν hv hv0 heigen
  linarith

/-- Hence each real transverse eigenmode of the continuous linearized flow,
written explicitly as exp (t * ν) • v, decays to zero. This is an
eigenmode theorem, not yet construction of the full operator semigroup. -/
theorem transverse_jacobian_eigenmode_tendsto_zero
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    (P A : E →L[ℝ] E) (α ν : ℝ) (hsmall : |α| * ‖A‖ < 1)
    {v : E} (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedJacobian P A α v = ν • v) :
    Filter.Tendsto (fun t : ℝ => Real.exp (t * ν) • v)
      Filter.atTop (nhds 0) := by
  have hν : ν < 0 :=
    transverse_jacobian_eigenvalue_neg P A α ν hsmall hv hv0 heigen
  have hpos : 0 < -ν := neg_pos.mpr hν
  have htop : Filter.Tendsto (fun t : ℝ => t * (-ν))
      Filter.atTop Filter.atTop :=
    Filter.Tendsto.atTop_mul_const hpos Filter.tendsto_id
  have hlin : Filter.Tendsto (fun t : ℝ => t * ν)
      Filter.atTop Filter.atBot := by
    have heq : (fun t : ℝ => t * ν) = fun t => -(t * (-ν)) := by
      funext t
      ring
    rw [heq]
    exact Filter.tendsto_neg_atTop_atBot.comp htop
  have hexp : Filter.Tendsto (fun t : ℝ => Real.exp (t * ν))
      Filter.atTop (nhds 0) :=
    Real.tendsto_exp_atBot.comp hlin
  simpa using hexp.smul_const v

/-- The decay theorem is therefore genuinely a statement about the orbit of
the full complete-Jacobian operator semigroup. -/
theorem jacobianSemigroup_eigenmode_tendsto_zero
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (P A : E →L[ℝ] E) (α ν : ℝ) (hsmall : |α| * ‖A‖ < 1)
    {v : E} (hv : P v = 0) (hv0 : v ≠ 0)
    (heigen : combinedJacobian P A α v = ν • v) :
    Filter.Tendsto (fun t : ℝ => jacobianSemigroup P A α t v)
      Filter.atTop (nhds 0) := by
  have hmode :=
    transverse_jacobian_eigenmode_tendsto_zero
      P A α ν hsmall hv hv0 heigen
  convert hmode using 1
  funext t
  exact jacobianSemigroup_apply_eigen P A α ν t heigen

/-! ### The limitation of linear reflexive maps -/

variable {V : Type*} [AddCommGroup V] [Module ℝ V]

/-- Every linear self-update has a fixed point it cannot remove: the
origin (proposition:bk1_limitation_linear_reflexive_maps, first half). -/
theorem linear_has_fixed_point (f : V →ₗ[ℝ] V) : ∃ x, f x = x :=
  ⟨0, map_zero f⟩

/-- The fixed-point set of a linear update is closed under the linear
structure: linear reflexivity cannot even bend its own fixed locus. -/
theorem linear_fixed_points_closed (f : V →ₗ[ℝ] V) {x y : V} (r : ℝ)
    (hx : f x = x) (hy : f y = y) :
    f (x + y) = x + y ∧ f (r • x) = r • x := by
  constructor
  · rw [map_add, hx, hy]
  · rw [map_smul, hx]

/-- No pipeline of linear updates escapes: the composition still fixes
the origin. -/
theorem linear_pipeline_fixes_zero (f g : V →ₗ[ℝ] V) :
    (g ∘ₗ f) 0 = 0 :=
  map_zero _

/-- The contrast that makes the limitation real: a single AFFINE
(nonlinear) update has no fixed point at all — nonlinear reflexivity
can clear its own fixed locus; linear reflexivity provably cannot. -/
theorem affine_escapes_fixed_points : ∀ x : ℝ, x + 1 ≠ x := by
  intro x h
  linarith

/-! ### Paradox-triggered emergence -/

/-- A frame (set of available observables) resolves a demanded
distinction when some observable in it separates the pair. -/
def Resolves (Obs : Set (M → Prop)) (p q : M) : Prop :=
  ∃ f ∈ Obs, f p ∧ ¬ f q

/-- **Unresolvable within the frame**
(definition:bk1_paradox_triggered_emergence, first clause): if every
in-frame observable agrees on the pair, no in-frame reframing resolves
the contradiction. -/
theorem paradox_unresolvable_within {Obs : Set (M → Prop)} {p q : M}
    (hagree : ∀ f ∈ Obs, (f p ↔ f q)) : ¬ Resolves Obs p q := by
  rintro ⟨f, hf, hfp, hfq⟩
  exact hfq ((hagree f hf).mp hfp)

/-- **The extension resolves** (the second clause, and the minimal
extension of lemma:bk1_contradiction_resolution_principle,
constructive): adjoining the single indicator observable to the frame
resolves any genuine distinction. -/
theorem extension_resolves (Obs : Set (M → Prop)) {p q : M} (hpq : p ≠ q) :
    Resolves (insert (fun x => x = p) Obs) p q :=
  ⟨fun x => x = p, Set.mem_insert _ _, rfl, fun h => hpq h.symm⟩

/-- **Paradoxical symmetry breaking**
(lemma:bk1_paradoxical_symmetry_breaking): every in-frame observable is
invariant under the swap carrying p to q — that is the symmetry — and
ANY observable resolving the paradox must break it: resolution and
swap-invariance are incompatible. The paradox corresponds to a symmetry
that must be broken to achieve resolution, exactly. -/
theorem resolution_breaks_symmetry {p q : M} (σ : M → M) (hσ : σ p = q)
    (f : M → Prop) (hres : f p ∧ ¬ f q) :
    ¬ ∀ x, (f (σ x) ↔ f x) := by
  intro hinv
  exact hres.2 (hσ ▸ (hinv p).mpr hres.1)

end ForcingAnalysis.ScholiumDyn
