"""FabricPC guard witness: the triple-guarded predictive-coding contract
(ForcingAnalysis/FabricPCGuard.lean), measured (ledger LPS-O6, condition 3).

Trajectories are generated by the local reference implementation of the
contract dynamics — guardedStep(eps, delta, sigma, rho) =
(1-eps-delta)*rho + eps*sigma + delta*uniform — the Lean-side update the
external FabricPC codebase is contracted to respect. The external
codebase is NOT run here (that correspondence is LPS-O6's remaining
sliver); what is measured is that the certified guard theorems hold at
machine scale on a declared regime, plus the dark-room negative control
showing the unguarded (delta=0) dynamics genuinely exhibits the failure
the guard exists to prevent.

Declared regime: n=6 states, energies H ~ U[0,2] (seeded), inverse
temperatures beta in {0.5, 2, 8, 32}, guard rates eps=0.3, delta=0.1,
T=200 steps, random initial density.

Checks (each mirrors a named Lean theorem):
  G1  novelty floor (novelty_floor / guarded_floor_all_temperatures):
      every state keeps mass >= delta/n at every step >= 1, at every beta.
  G1' dark room (negative control; Book2.gibbs_concentrates): at beta=32
      the UNGUARDED relaxation collapses the minimum mass far below the
      floor while the guarded run holds it.
  G2  Moloch budget (guarded_kl_le / guarded_sequence_bounded): KL to the
      Gibbs target never exceeds max(initial KL, KL(uniform||target)),
      and the per-step contraction inequality holds at every step.
  G3  no arrival (guarded_arrival_iff_uniform): the trajectory converges
      to the guarded fixed point rho* = (eps*sigma + delta*u)/(eps+delta),
      whose L1 offset from the pure-prediction target equals
      (delta/(eps+delta)) * ||u - sigma||_1 exactly — approach without
      arrival, with the offset the declared price of imagination.

Output: verification/fabricpc_witness.json. Exit 1 on any violation.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

OUT = Path(__file__).resolve().parents[1] / "fabricpc_witness.json"

N = 6
EPS = 0.3
DELTA = 0.1
BETAS = [0.5, 2.0, 8.0, 32.0]
STEPS = 200
SEED = 20260713


def gibbs(beta: float, H: np.ndarray) -> np.ndarray:
    w = np.exp(-beta * H)
    return w / w.sum()


def kl(rho: np.ndarray, sigma: np.ndarray) -> float:
    mask = rho > 0
    return float(np.sum(rho[mask] * np.log(rho[mask] / sigma[mask])))


def guarded_step(eps: float, delta: float, sigma: np.ndarray,
                 rho: np.ndarray) -> np.ndarray:
    return (1 - eps - delta) * rho + eps * sigma + delta / len(rho)


def main() -> int:
    rng = np.random.default_rng(SEED)
    H = rng.uniform(0.0, 2.0, size=N)
    rho0 = rng.dirichlet(np.ones(N))
    uniform = np.full(N, 1.0 / N)
    floor = DELTA / N

    result = {"schema": "sketched.fabricpc-witness.v1",
              "regime": {"n": N, "eps": EPS, "delta": DELTA,
                         "betas": BETAS, "steps": STEPS, "seed": SEED},
              "per_beta": {}, "checks": {}}
    ok = True

    worst_floor_margin = float("inf")
    worst_budget_excess = -float("inf")
    worst_step_excess = -float("inf")
    worst_fp_dist = -float("inf")
    worst_offset_err = -float("inf")
    min_no_arrival_ratio = float("inf")

    for beta in BETAS:
        sigma = gibbs(beta, H)
        kl_u = kl(uniform, sigma)
        budget = max(kl(rho0, sigma), kl_u)
        rho = rho0.copy()
        min_mass = float("inf")
        for _ in range(STEPS):
            prev_kl = kl(rho, sigma)
            rho = guarded_step(EPS, DELTA, sigma, rho)
            min_mass = min(min_mass, float(rho.min()))
            worst_budget_excess = max(worst_budget_excess,
                                      kl(rho, sigma) - budget)
            worst_step_excess = max(
                worst_step_excess,
                kl(rho, sigma) - ((1 - EPS - DELTA) * prev_kl + DELTA * kl_u))
        worst_floor_margin = min(worst_floor_margin, min_mass - floor)

        fixed_pt = (EPS * sigma + DELTA * uniform) / (EPS + DELTA)
        fp_dist = float(np.abs(rho - fixed_pt).sum())
        worst_fp_dist = max(worst_fp_dist, fp_dist)
        offset = float(np.abs(fixed_pt - sigma).sum())
        predicted = DELTA / (EPS + DELTA) * float(np.abs(uniform - sigma).sum())
        worst_offset_err = max(worst_offset_err, abs(offset - predicted))
        dist_to_target = float(np.abs(rho - sigma).sum())
        if predicted > 1e-9:
            min_no_arrival_ratio = min(min_no_arrival_ratio,
                                       dist_to_target / predicted)
        result["per_beta"][str(beta)] = {
            "min_mass": min_mass, "floor": floor,
            "kl_budget": budget, "final_kl": kl(rho, sigma),
            "fixed_point_dist": fp_dist,
            "offset_from_target": offset, "offset_predicted": predicted,
        }

    # dark-room negative control at the coldest beta: unguarded collapse
    beta = BETAS[-1]
    sigma = gibbs(beta, H)
    rho = rho0.copy()
    for _ in range(STEPS):
        rho = guarded_step(EPS, 0.0, sigma, rho)  # delta = 0: no imagination
    dark_min = float(rho.min())
    result["dark_room"] = {"beta": beta, "unguarded_min_mass": dark_min,
                           "guarded_floor": floor,
                           "collapse_ratio": dark_min / floor}

    checks = {
        "G1_novelty_floor": worst_floor_margin >= -1e-12,
        "G1_dark_room_collapses": dark_min < floor * 1e-3,
        "G2_budget_invariant": worst_budget_excess <= 1e-9,
        "G2_per_step_contraction": worst_step_excess <= 1e-9,
        "G3_converges_to_guarded_fixed_point": worst_fp_dist <= 1e-10,
        "G3_offset_exact": worst_offset_err <= 1e-12,
        "G3_no_arrival": min_no_arrival_ratio >= 0.5,
    }
    result["checks"] = checks
    result["measurements"] = {
        "worst_floor_margin": worst_floor_margin,
        "worst_budget_excess": worst_budget_excess,
        "worst_step_excess": worst_step_excess,
        "worst_fixed_point_dist": worst_fp_dist,
        "worst_offset_error": worst_offset_err,
        "min_no_arrival_ratio": min_no_arrival_ratio,
        "dark_room_min_mass": dark_min,
    }
    ok = all(checks.values())
    result["verdict"] = "pass" if ok else "FAIL"

    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    for name, passed in checks.items():
        print(f"{name}: {'PASS' if passed else 'FAIL'}")
    print(f"dark room: unguarded min mass {dark_min:.3e} vs guarded floor "
          f"{floor:.3e} (ratio {dark_min / floor:.2e})")
    print(f"no-arrival offset: predicted delta/(eps+delta)*||u-sigma||_1 "
          f"matches measured to {worst_offset_err:.2e}")
    print(f"verdict: {result['verdict']}  ->  {OUT}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
